// Tam kategori segmentleri ve ayar etiketleri Türkçe sözlüğü
const categories = {
  "Accessible Diff Viewer": "Erişilebilir Fark Görüntüleyici",
  "Accounts": "Hesaplar",
  "Action": "Eylem",
  "Actions": "Eylemler",
  "Activity": "Aktivite",
  "Activity Bar": "Aktivite Çubuğu",
  "Activity Bar Location": "Aktivite Çubuğu Konumu",
  "Attach": "Ekle",
  "Automation Profile": "Otomasyon Profili",
  "Auxiliary Activity Bar": "İkincil Aktivite Çubuğu",
  "Auxiliary Activity Bar Location": "İkincil Aktivite Çubuğu Konumu",
  "Auxiliaryactivity": "İkincil Aktivite",
  "Auxiliarybar": "İkincil Çubuk",
  "Banner": "Başlık Bandı",
  "Bracket Pair Colorization": "Ayraç Çifti Renklendirmesi",
  "Chat": "Sohbet",
  "Chat Agent Tools": "Sohbet Ajanı Araçları",
  "Cloud Changes": "Bulut Değişiklikleri",
  "Code Action Widget": "Kod Eylemi Pencere Öğesi",
  "Code Actions": "Kod Eylemleri",
  "Command": "Komut",
  "Command Palette": "Komut Paleti",
  "Comments": "Yorumlar",
  "Compare Editor": "Karşılaştırma Düzenleyicisi",
  "Config": "Yapılandırma",
  "Configure": "Yapılandır",
  "Contexts": "Bağlamlar",
  "Continue Chat In Session": "Oturumda Sohbete Devam Et",
  "Continue On": "Şurada Devam Et",
  "Contrib": "Katkı",
  "Contribution": "Katkı",
  "Contributions": "Katkılar",
  "Controller": "Denetleyici",
  "Custom Labels": "Özel Etiketler",
  "Debug": "Hata Ayıklama",
  "Decorations": "Süslemeler",
  "Default": "Varsayılan",
  "Default Profile": "Varsayılan Profil",
  "Density": "Yoğunluk",
  "Dev": "Geliştirici",
  "Developer": "Geliştirici",
  "Dialog": "İletişim Kutusu",
  "Diff Editor": "Fark Düzenleyici",
  "Diff Review": "Fark İncelemesi",
  "Dirtydiff": "Kaydedilmemiş Farklar",
  "Drop Into Editor": "Düzenleyiciye Bırakma",
  "Edit": "Düzenle",
  "Edit Sessions": "Düzenleme Oturumları",
  "Editor": "Metin Düzenleyici",
  "Editor Dictation": "Düzenleyici Dikte",
  "Editorinputs": "Düzenleyici Girdileri",
  "Editors": "Düzenleyiciler",
  "Edits": "Düzenlemeler",
  "Emmet": "Emmet",
  "Empty": "Boş",
  "Env": "Ortam",
  "Experimental": "Deneysel",
  "Explorer": "Gezgin",
  "Extension": "Uzantı",
  "Extension Host Profiler": "Uzantı Ana Bilgisayarı Profil Oluşturucu",
  "Extensioneditor": "Uzantı Düzenleyicisi",
  "Extensions": "Uzantılar",
  "External": "Harici",
  "Features": "Özellikler",
  "File Nesting": "Dosya Yuvalama",
  "File View": "Dosya Görünümü",
  "Files": "Dosyalar",
  "Find": "Bul",
  "Focus": "Odak",
  "Font": "Yazı Tipi",
  "Font Ligatures": "Yazı Tipi Bitiştirmeleri",
  "Format Document": "Belgeyi Biçimlendir",
  "Format Selection": "Seçimi Biçimlendir",
  "Formatting": "Biçimlendirme",
  "Gallery": "Galeri",
  "Git": "Git",
  "Goto Location": "Konuma Git",
  "Goto Next Symbol From Result": "Sonuçtan Sonraki Simgeye Git",
  "Graph": "Grafik",
  "Guides": "Kılavuzlar",
  "History": "Geçmiş",
  "Hover": "Üzerine Gelme (Hover)",
  "In Place Replace": "Yerinde Değiştir",
  "Initial Hint": "İlk İpucu",
  "Inlay Hints": "Satır İçi İpuçları",
  "Inline Suggest": "Satır İçi Öneriler",
  "Input": "Girdi",
  "Install": "Yükle",
  "Integrated": "Tümleşik",
  "Interactive Playground": "Etkileşimli Alan",
  "Language": "Dil",
  "Language Detection Opened Languages": "Dil Algılama Açık Diller",
  "Layout": "Düzen",
  "Layout Control": "Düzen Denetimi",
  "Lightbulb": "Ampul Önerisi",
  "Limit": "Sınır",
  "List": "Liste",
  "Local History": "Yerel Geçmiş",
  "Log Change Reason": "Değişiklik Nedenini Günlüğe Kaydet",
  "Log Fetch": "Günlük Getirme",
  "Marker": "İşaretleyici",
  "Markers": "İşaretleyiciler",
  "Mcp": "MCP",
  "Mcp Server": "MCP Sunucusu",
  "Menu": "Menü",
  "Menubar": "Menü Çubuğu",
  "Minimap": "Mini Harita",
  "Models": "Modeller",
  "Multi Diff Editor": "Çoklu Dosya Fark Düzenleyicisi",
  "Navigation Control": "Gezinme Denetimi",
  "Navigible Container": "Gezinilebilir Kapsayıcı",
  "New": "Yeni",
  "Notebook": "Not Defteri",
  "Notification": "Bildirim",
  "Notifications": "Bildirimler",
  "Open Editors": "Açık Düzenleyiciler",
  "Open Url": "URL Aç",
  "Output": "Çıktı",
  "Overlay Widget": "Katman Pencere Öğesi",
  "Padding": "İç Boşluk",
  "Panel": "Panel",
  "Panelpart": "Panel Bölümü",
  "Parameter Hints": "Parametre İpuçları",
  "Partial Matches": "Kısmi Eşleşmeler",
  "Participants": "Katılımcılar",
  "Parts": "Bölümler",
  "Paste As": "Farklı Yapıştır",
  "Placeholder": "Yer Tutucu",
  "Prefer Tree Sitter": "Tree-sitter Tercih Et",
  "Preferences": "Tercihler",
  "Problems": "Sorunlar",
  "Profile": "Profil",
  "Profiles": "Profiller",
  "Pty Host": "Pty Ana Bilgisayarı",
  "Quick Access": "Hızlı Erişim",
  "Quick Diff Providers": "Hızlı Fark Sağlayıcıları",
  "Quick Input": "Hızlı Girdi",
  "Quick Open": "Hızlı Aç",
  "Quickchat": "Hızlı Sohbet",
  "Refactoring": "Yeniden Düzenleme",
  "Reference Search": "Başvuru Araması",
  "Registry": "Kayıt Defteri",
  "Remote": "Uzak (Remote)",
  "Remote Indicator": "Uzak Bağlantı Göstergesi",
  "Remote Tunnel": "Uzak Tünel",
  "Rename": "Yeniden Adlandır",
  "Repl": "REPL",
  "Replace": "Değiştir",
  "Restricted Mode": "Kısıtlı Mod",
  "Ripgrep": "Ripgrep",
  "Runtime Extensions": "Çalışma Zamanı Uzantıları",
  "Sash": "Ayırıcı Çizgi (Sash)",
  "Scm": "Kaynak Denetimi",
  "Scrollbar": "Kaydırma Çubuğu",
  "Search": "Arama",
  "Search Editor": "Arama Düzenleyicisi",
  "Search View": "Arama Görünümü",
  "Secondary Side Bar": "İkincil Kenar Çubuğu",
  "Security": "Güvenlik",
  "Semantic Highlighting": "Anlamsal Vurgulama",
  "Servers": "Sunucular",
  "Settings": "Ayarlar",
  "Share": "Paylaş",
  "Shell Integration": "Kabuk Tümleştirmesi",
  "Side Bar": "Kenar Çubuğu",
  "Sidebar": "Kenar Çubuğu",
  "Simple Dialog": "Basit İletişim Kutusu",
  "Smart Select": "Akıllı Seçim",
  "Snippets": "Kod Parçacıkları",
  "Speech": "Konuşma",
  "Status Bar": "Durum Çubuğu",
  "Statusbar": "Durum Çubuğu",
  "Sticky Scroll": "Sabit Kaydırma (Sticky Scroll)",
  "Suggest": "Öneriler",
  "Suggestions": "Öneriler",
  "Sync": "Eşitleme",
  "Sync Data": "Veri Eşitleme",
  "Tab": "Sekme",
  "Tabs": "Sekmeler",
  "Tasks": "Görevler",
  "Terminal": "Terminal",
  "Test Explorer": "Test Gezgini",
  "Test Results": "Test Sonuçları",
  "Testing": "Test",
  "Tips": "İpuçları",
  "Tree": "Ağaç Görünümü",
  "Tree View": "Ağaç Görünümü",
  "Troubleshoot Issue": "Sorun Gider",
  "Trust": "Güven",
  "Trusted Domains": "Güvenilen Etki Alanları",
  "Unicode Highlight": "Unicode Vurgulama",
  "Unsupported Connection": "Desteklenmeyen Bağlantı",
  "Untitled": "Başlıksız",
  "Url": "URL",
  "User Data": "Kullanıcı Verileri",
  "User Data Sync": "Kullanıcı Verisi Eşitleme",
  "Valid Overlay": "Geçerli Katman",
  "View": "Görünüm",
  "View Container": "Görünüm Kapsayıcısı",
  "Viewlet": "Görünüm Bölümü",
  "Views": "Görünümler",
  "Walkthroughs": "Tanıtımlar",
  "Webview": "Web Görünümü",
  "Webvieweditor": "Web Görünümü Düzenleyicisi",
  "Welcome": "Karşılama",
  "Welcome Page": "Karşılama Sayfası",
  "Widget": "Pencere Öğesi",
  "Window": "Pencere",
  "Word Highlight": "Sözcük Vurgulama",
  "Workbench": "Çalışma Yeri",
  "Accessibility": "Erişilebilirlik",
  "Accessible View": "Erişilebilir Görünüm",
  "Agent": "Ajan",
  "Checkpoints": "Kontrol Noktaları",
  "Command Center": "Komut Merkezi",
  "Console": "Konsol",
  "Delays": "Gecikmeler",
  "Detect Participant": "Katılımcı Algıla",
  "Diff": "Fark",
  "Dim Unfocused": "Odaksızları Karart",
  "Disassembly View": "Ayrıştırma Görünümü",
  "Editing": "Düzenleme",
  "Extension Unification": "Uzantı Birleştirmesi",
  "Hide Unchanged Regions": "Değişmemiş Bölgeleri Gizle",
  "Implicit Context": "Örtük Bağlam",
  "Internal": "Dahili",
  "Navigation": "Gezinme",
  "Repl Editor": "REPL Düzenleyicisi",
  "Repositories": "Depolar",
  "Results View": "Sonuçlar Görünümü",
  "Send Elements To Chat": "Öğeleri Sohbete Gönder",
  "Signal Options": "Sinyal Seçenekleri",
  "Signals": "Sinyaller",
  "Status Widget": "Durum Pencere Öğesi",
  "Terminal Profile": "Terminal Profili",
  "Thinking": "Düşünme",
  "Thread": "İş Parçacığı",
  "Todo List Tool": "Yapılacaklar Listesi Aracı",
  "Tools": "Araçlar",
  "Undo Requests": "Geri Alma İstekleri",
  "Verbosity": "Ayrıntı Düzeyi",
  "Voice": "Ses",
  "Working Sets": "Çalışma Kümeleri",
  "Workspace": "Çalışma Alanı",
  "Workspace Trust": "Çalışma Alanı Güveni",
  "Antigravity Editor": "Antigravity Düzenleyici",
  "Antigravity Remote - Dev Containers": "Antigravity Uzak - Geliştirme Kapsayıcıları",
  "Antigravity Remote - SSH": "Antigravity Uzak - SSH",
  "Media Previewer": "Medya Önizleyici",
  "JavaScript Debugger": "JavaScript Hata Ayıklayıcısı",
  "Codex Settings": "Codex Ayarları",
  "Claude Code": "Claude Code",
  "Problem Matchers": "Sorun Eşleştiricileri",
  "Smart Scroll": "Akıllı Kaydırma",
  "Breadcrumbs": "İçerik Haritası (Breadcrumbs)",
  "Zen Mode": "Zen Modu",
  "Screencast Mode": "Ekran Yayını Modu",
  "Settings Sync": "Ayar Senkronizasyonu"
};

const settings = {
  "Independent Color Pool Per Bracket Type": "Ayraç Türü Başına Bağımsız Renk Havuzu",
  "Trigger On Focus Change": "Odak Değiştiğinde Tetikle",
  "Include Nearby Quick Fixes": "Yakındaki Hızlı Düzeltmeleri Dahil Et",
  "Show Headers": "Başlıkları Göster",
  "Enabled": "Etkin",
  "Auto Indent": "Otomatik Girintileme",
  "Auto Indent On Paste": "Yapıştırırken Otomatik Girintile",
  "Auto Indent On Paste Within String": "Dizgi İçinde Yapıştırırken Otomatik Girintile",
  "Auto Surround": "Otomatik Çevreleme",
  "Auto Closing Brackets": "Ayraçları Otomatik Kapat",
  "Auto Closing Comments": "Yorumları Otomatik Kapat",
  "Auto Closing Delete": "Ayraç Silmeyi Otomatikleştir",
  "Auto Closing Overtype": "Üzerine Yazmayı Otomatikleştir",
  "Auto Closing Quotes": "Tırnakları Otomatik Kapat",
  "Accessibility Page Size": "Erişilebilirlik Sayfa Boyutu",
  "Accessibility Support": "Erişilebilirlik Desteği",
  "Allow Variable Fonts": "Değişken Yazı Tiplerine İzin Ver",
  "Allow Variable Fonts In Accessibility Mode": "Erişilebilirlik Modunda Değişken Yazı Tiplerine İzin Ver",
  "Allow Variable Line Heights": "Değişken Satır Yüksekliklerine İzin Ver",
  "Code Actions On Save": "Kaydederken Kod Eylemleri",
  "Code Lens": "CodeLens",
  "Color Decorators": "Renk Dekoratörleri",
  "Color Theme": "Renk Teması",
  "Column Selection": "Sütun Seçimi",
  "Comments": "Yorumlar",
  "Confirm Delete": "Silmeyi Onayla",
  "Copy With Syntax Highlighting": "Sözdizimi Vurgusuyla Kopyala",
  "Cursor Blinking": "İmleç Yanıp Sönmesi",
  "Cursor Smooth Caret Animation": "İmleç Yumuşak Hareket Animasyonu",
  "Cursor Style": "İmleç Stili",
  "Cursor Surrounding Lines": "İmleç Çevre Satırları",
  "Cursor Width": "İmleç Genişliği",
  "Default Formatter": "Varsayılan Biçimlendirici",
  "Definition Link Opens In Peek": "Tanım Bağlantısını Göz Atma Panelinde Aç",
  "Detect Indentation": "Girintiyi Otomatik Algıla",
  "Drag And Drop": "Sürükle ve Bırak",
  "Empty Selection Clipboard": "Boş Seçimde Satırı Kopyala",
  "Enable Preview": "Önizlemeyi Etkinleştir",
  "Fast Scroll Sensitivity": "Hızlı Kaydırma Duyarlılığı",
  "Find": "Bul",
  "Folding": "Kod Katlama",
  "Folding Imports By Default": "İçeri Aktarmaları Varsayılan Olarak Katla",
  "Folding Strategy": "Katlama Stratejisi",
  "Font Family": "Yazı Tipi Ailesi",
  "Font Ligatures": "Yazı Tipi Bitiştirmeleri",
  "Font Size": "Yazı Tipi Boyutu",
  "Font Weight": "Yazı Tipi Kalınlığı",
  "Format On Paste": "Yapıştırırken Biçimlendir",
  "Format On Save": "Kaydederken Biçimlendir",
  "Format On Save Mode": "Kaydederken Biçimlendirme Modu",
  "Format On Type": "Yazarken Biçimlendir",
  "Glyph Margin": "Simge Kenar Boşluğu",
  "Guides": "Kılavuzlar",
  "Hover": "Üzerine Gelme (Hover)",
  "Icon Theme": "Simge Teması",
  "Inlay Hints": "Satır İçi İpuçları",
  "Inline Suggest": "Satır İçi Öneriler",
  "Insert Spaces": "Boşluk Ekle",
  "Letter Spacing": "Harf Boşluğu",
  "Lightbulb": "Ampul Önerisi",
  "Line Height": "Satır Yüksekliği",
  "Line Numbers": "Satır Numaraları",
  "Linked Editing": "Bağlantılı Düzenleme",
  "Links": "Bağlantılar",
  "Match Brackets": "Eşleşen Ayraçları Vurgula",
  "Minimap": "Mini Harita",
  "Mouse Wheel Scroll Sensitivity": "Fare Tekerleği Kaydırma Duyarlılığı",
  "Mouse Wheel Zoom": "Fare Tekerleğiyle Yakınlaştırma",
  "Multi Cursor Modifier": "Çoklu İmleç Değiştirici Tuşu",
  "Occurrences Highlight": "Eşleşmeleri Vurgula",
  "Padding": "İç Boşluk",
  "Quick Suggestions": "Hızlı Öneriler",
  "Render Control Characters": "Denetim Karakterlerini Göster",
  "Render Line Highlight": "Etkin Satırı Vurgula",
  "Render Whitespace": "Boşluk Karakterlerini Göster",
  "Rulers": "Cetveller",
  "Scroll Beyond Last Column": "Son Sütunun Ötesine Kaydır",
  "Scroll Beyond Last Line": "Son Satırın Ötesine Kaydır",
  "Selection Highlight": "Seçimi Vurgula",
  "Semantic Highlighting": "Anlamsal Vurgulama",
  "Show Folding Controls": "Katlama Denetimlerini Göster",
  "Smooth Scrolling": "Yumuşak Kaydırma",
  "Snippet Suggestions": "Kod Parçacığı Önerileri",
  "Sticky Scroll": "Sabit Kaydırma (Sticky Scroll)",
  "Suggest": "Öneriler",
  "Suggest On Trigger Characters": "Tetikleyici Karakterlerde Öner",
  "Suggest Selection": "Öneri Seçimi",
  "Tab Completion": "Sekmeyle Tamamlama",
  "Tab Size": "Sekme Boyutu",
  "Unicode Highlight": "Unicode Karakter Vurgulama",
  "Unusual Line Terminators": "Olağan Dışı Satır Sonlandırıcılar",
  "Word Based Suggestions": "Kelime Tabanlı Öneriler",
  "Word Separators": "Kelime Ayırıcılar",
  "Word Wrap": "Sözcük Kaydırma",
  "Word Wrap Column": "Sözcük Kaydırma Sütunu",
  "Wrapping Indent": "Kaydırma Girintisi",
  "Zoom Level": "Yakınlaştırma Düzeyi",
  "Auto Save": "Otomatik Kaydet",
  "Auto Save Delay": "Otomatik Kaydetme Gecikmesi",
  "Code Lens Font Family": "CodeLens Yazı Tipi Ailesi",
  "Code Lens Font Size": "CodeLens Yazı Tipi Boyutu",
  "Color Decorators Activated On": "Renk Dekoratörlerinin Etkinleştirilme Koşulu",
  "Default Color Decorators": "Varsayılan Renk Dekoratörleri",
  "Color Decorators Limit": "Renk Dekoratörü Sınırı",
  "Cursor Surrounding Lines Style": "İmleç Çevre Satırları Stili",
  "Cursor Height": "İmleç Yüksekliği",
  "Disable Layer Hinting": "Katman İpucunu Devre Dışı Bırak",
  "Disable Monospace Optimizations": "Eşaralıklı Yazı Tipi İyileştirmelerini Devre Dışı Bırak",
  "Dom Read Only": "DOM Salt Okunur",
  "Drop Into Editor": "Düzenleyiciye Bırakma",
  "Edit Context": "Düzenleme Bağlamı",
  "Experimental Gpu Acceleration": "Deneysel GPU Hızlandırması",
  "Experimental Whitespace Rendering": "Deneysel Boşluk Oluşturma",
  "Fixed Overflow Widgets": "Sabit Taşma Pencere Öğeleri",
  "Folding Highlight": "Katlama Vurgusu",
  "Folding Maximum Regions": "En Fazla Katlanabilir Bölge Sayısı",
  "Unfold On Click After End Of Line": "Satır Sonuna Tıklandığında Katlamayı Aç",
  "Font Info": "Yazı Tipi Bilgisi",
  "Font Variations": "Yazı Tipi Çeşitleri",
  "Goto Location": "Konuma Git",
  "Hide Cursor In Overview Ruler": "Genel Bakış Cetvelinde İmleci Gizle",
  "In Diff Editor": "Fark Düzenleyicisinde",
  "Line Decorations Width": "Satır Süslemeleri Genişliği",
  "Line Numbers Min Chars": "Satır Numaraları En Az Karakter Sayısı",
  "Mouse Style": "Fare Stili",
  "Multi Cursor Merge Overlapping": "Üst Üste Binen Çoklu İmleçleri Birleştir",
  "Mouse Middle Click Action": "Fare Orta Tuş Eylemi",
  "Multi Cursor Paste": "Çoklu İmleç Yapıştırma",
  "Multi Cursor Limit": "Çoklu İmleç Sınırı",
  "Occurrences Highlight Delay": "Eşleşmeleri Vurgulama Gecikmesi",
  "Overtype Cursor Style": "Üzerine Yazma İmleç Stili",
  "Overtype On Paste": "Yapıştırırken Üzerine Yaz",
  "Overview Ruler Border": "Genel Bakış Cetveli Kenarlığı",
  "Overview Ruler Lanes": "Genel Bakış Cetveli Şeritleri",
  "Paste As": "Farklı Yapıştır",
  "Parameter Hints": "Parametre İpuçları",
  "Peek Widget Default Focus": "Göz Atma Pencere Öğesi Varsayılan Odağı",
  "Placeholder": "Yer Tutucu",
  "Quick Suggestions Delay": "Hızlı Öneriler Gecikmesi",
  "Read Only": "Salt Okunur",
  "Read Only Message": "Salt Okunur İletisi",
  "Rename On Type": "Yazarken Yeniden Adlandır",
  "Render Rich Screen Reader Content": "Zengin Ekran Okuyucu İçeriğini Göster",
  "Render Final Newline": "Son Satır Sonunu Göster",
  "Render Line Highlight Only When Focus": "Etkin Satırı Yalnızca Odaklandığında Vurgula",
  "Render Validation Decorations": "Doğrulama Süslemelerini Göster",
  "Reveal Horizontal Right Padding": "Yatay Sağ İç Boşluğu Göster",
  "Rounded Selection": "Yuvarlatılmış Seçim Köşeleri",
  "Scrollbar": "Kaydırma Çubuğu",
  "Scroll Predominant Axis": "Baskın Eksende Kaydır",
  "Selection Clipboard": "Seçim Panosu",
  "Selection Highlight Max Length": "Seçim Vurgusu En Fazla Uzunluğu",
  "Selection Highlight Multiline": "Çok Satırlı Seçimleri Vurgula",
  "Select On Line Numbers": "Satır Numaralarından Seç",
  "Show Unused": "Kullanılmayanları Göster",
  "Smart Select": "Akıllı Seçim",
  "Sticky Tab Stops": "Sabit Sekme Durakları",
  "Stop Rendering Line After": "Satırı Şu Karakterden Sonra İşlemeyi Durdur",
  "Suggest Font Size": "Öneri Yazı Tipi Boyutu",
  "Suggest Line Height": "Öneri Satır Yüksekliği",
  "Tab Index": "Sekme İndeksi",
  "Trim Whitespace On Delete": "Silerken Boşlukları Kırp",
  "Unicode Highlighting": "Unicode Vurgulama",
  "Use Shadow DOM": "Shadow DOM Kullan",
  "Use Tab Stops": "Sekme Duraklarını Kullan",
  "Word Break": "Sözcük Bölme",
  "Word Segmenter Locales": "Sözcük Bölücü Yerel Ayarları",
  "Word Wrap Break After Characters": "Sözcük Kaydırmada Sonrasına Bölünecek Karakterler",
  "Word Wrap Break Before Characters": "Sözcük Kaydırmada Öncesine Bölünecek Karakterler",
  "Word Wrap Override1": "Sözcük Kaydırma Geçersiz Kılma 1",
  "Word Wrap Override2": "Sözcük Kaydırma Geçersiz Kılma 2",
  "Wrapping Strategy": "Kaydırma Stratejisi",
  "Show Deprecated": "Kullanımdan Kaldırılanları Göster",
  "Inertial Scroll": "Eylemsizlik Kaydırması",
  "Wrap On Escaped Line Feeds": "Kaçışlı Satır Sonlarında Kaydır",
  "Effective Cursor Style": "Geçerli İmleç Stili",
  "Editor Class Name": "Düzenleyici Sınıf Adı",
  "Pixel Ratio": "Piksel Oranı",
  "Tab Focus Mode": "Sekme Odaklama Modu",
  "Layout Info": "Düzen Bilgisi",
  "Wrapping Info": "Kaydırma Bilgisi",
  "Inline Completions Accessibility Verbose": "Satır İçi Tamamlamalar Ayrıntılı Erişilebilirlik",
  "Effective Edit Context": "Geçerli Düzenleme Bağlamı",
  "Scroll On Middle Click": "Orta Tuşla Kaydır",
  "Effective Allow Variable Fonts": "Geçerli Değişken Yazı Tiplerine İzin Ver",
  "Accept Suggestion On Commit Character": "İşleme Karakterinde Öneriyi Kabul Et",
  "Accept Suggestion On Enter": "Enter Tuşuna Basıldığında Öneriyi Kabul Et",
  "Allow Overflow": "Taşmaya İzin Ver",
  "Aria Label": "Aria Etiketi",
  "Aria Required": "Aria Zorunlu",
  "Screen Reader Announce Inline Suggestion": "Ekran Okuyucu Satır İçi Öneriyi Seslendirsin",
  "Automatic Layout": "Otomatik Düzen",
  "Bracket Pair Colorization": "Ayraç Çifti Renklendirmesi",
  "Async Tokenization Logging": "Zaman Uyumsuz Belirteç Ayırma Günlüğü",
  "Async Tokenization Verification": "Zaman Uyumsuz Belirteç Ayırma Doğrulaması",
  "Async Tokenization": "Zaman Uyumsuz Belirteç Ayırma",
  "Tree Sitter Telemetry": "Tree-sitter Telemetrisi",
  "Prefer Tree Sitter": "Tree-sitter Tercih Et",
  "Ambiguous Characters": "Belirsiz Karakterler",
  "Invisible Characters": "Görünmez Karakterler",
  "Colorized Bracket Pairs": "Renklendirilmiş Ayraç Çiftleri",
  "Auto Find In Selection": "Seçim İçinde Otomatik Bul",
  "Seed Search String From Selection": "Arama Dizgisini Seçimden Başlat",
  "Global Find Clipboard": "Genel Bulma Panosu",
  "Add Extra Space On Top": "Üst Kısma Ekstra Boşluk Ekle",
  "Find On Type": "Yazarken Bul",
  "Max Line Count": "Maksimum Satır Sayısı",
  "Default Model": "Varsayılan Model",
  "Multiple Definitions": "Çoklu Tanımlar",
  "Multiple Type Definitions": "Çoklu Tür Tanımları",
  "Multiple Declarations": "Çoklu Bildirimler",
  "Multiple Implementations": "Çoklu Uygulamalar",
  "Multiple References": "Çoklu Başvurular",
  "Alternative Definition Command": "Alternatif Tanım Komutu",
  "Alternative Type Definition Command": "Alternatif Tür Tanımı Komutu",
  "Alternative Declaration Command": "Alternatif Bildirim Komutu",
  "Alternative Implementation Command": "Alternatif Uygulama Komutu",
  "Alternative Reference Command": "Alternatif Başvuru Komutu",
  "Peek Implementation": "Uygulamaya Gözat",
  "Go To Implementation": "Uygulamaya Git",
  "Peek Type Definition": "Tür Tanımına Gözat",
  "Go To Type Definition": "Tür Tanımına Git",
  "Peek Declaration": "Bildirime Gözat",
  "Reveal Declaration": "Bildirimi Göster",
  "Peek Definition": "Tanıma Gözat",
  "Reveal Definition": "Tanımı Göster",
  "Reveal Definition Aside": "Tanımı Yanda Göster",
  "Cursor Move On Type": "Yazarken İmleci Taşı",
  "Insert Space": "Boşluk Ekle",
  "Ignore Empty Lines": "Boş Satırları Yoksay",
  "Marker Decorations": "İşaretçi Süslemeleri",
  "Select All": "Tümünü Seç",
  "Contributions": "Katkılar",
  "Modes Registry": "Modlar Kayıt Defteri",
  "Replace History": "Değiştirme Geçmişi",
  "Hiding Delay": "Gizleme Gecikmesi",
  "Default Folding Range Provider": "Varsayılan Katlama Aralığı Sağlayıcısı",
  "Preferences": "Tercihler",
  "Show Drop Selector": "Bırakma Seçicisini Göster",
  "Bracket Pairs Horizontal": "Yatay Ayraç Çiftleri",
  "Highlight Active Bracket Pair": "Etkin Ayraç Çiftini Vurgula",
  "Highlight Active Indentation": "Etkin Girintiyi Vurgula",
  "Indentation": "Girinti",
  "Close On Key Press": "Tuşa Basıldığında Kapat",
  "Debug Watch Variable Announcements": "Hata Ayıkla İzle Değişken Duyurular",
  "Opacity": "Opaklık",
  "Hide Accessible View": "Erişilebilir Görünümü Gizle",
  "Open Chat Edited Files": "Sohbetle Düzenlenen Dosyaları Aç",
  "Auto Focus Repl Execution": "REPL Yürütmesine Otomatik Odaklan",
  "Read Last Execution Output": "Son Yürütme Çıktısını Oku",
  "Debounce Position Changes": "Konum Değişikliklerini Geciktir",
  "Error At Position": "Konumdaki Hata",
  "General": "Genel",
  "Warning At Position": "Konumdaki Uyarı",
  "Volume": "Ses Düzeyi",
  "Chat Edit Modified File": "Sohbet Düzenlemesiyle Değiştirilen Dosya",
  "Chat Request Sent": "Sohbet İsteği Gönderildi",
  "Chat Response Received": "Sohbet Yanıtı Alındı",
  "Chat User Action Required": "Sohbette Kullanıcı Eylemi Gerekli",
  "Clear": "Temizle",
  "Code Action Applied": "Kod Eylemi Uygulandı",
  "Code Action Triggered": "Kod Eylemi Tetiklendi",
  "Diff Line Deleted": "Fark Satırı Silindi",
  "Diff Line Inserted": "Fark Satırı Eklendi",
  "Diff Line Modified": "Fark Satırı Değiştirildi",
  "Edits Kept": "Düzenlemeler Korundu",
  "Edits Undone": "Düzenlemeler Geri Alındı",
  "Format": "Biçimlendir",
  "Line Has Breakpoint": "Satırda Kesme Noktası Var",
  "Line Has Error": "Satırda Hata Var",
  "Line Has Folded Area": "Satırda Katlanmış Alan Var",
  "Line Has Inline Suggestion": "Satırda Satır İçi Öneri Var",
  "Line Has Warning": "Satırda Uyarı Var",
  "Next Edit Suggestion": "Sonraki Düzenleme Önerisi",
  "No Inlay Hints": "Satır İçi İpuçları Yok",
  "Notebook Cell Completed": "Not Defteri Hücresi Tamamlandı",
  "Notebook Cell Failed": "Not Defteri Hücresi Başarısız Oldu",
  "On Debug Break": "Hata Ayıklama Durakladığında",
  "Position Has Error": "Konumda Hata Var",
  "Position Has Warning": "Konumda Uyarı Var",
  "Progress": "Progress",
  "Save": "Kaydet",
  "Task Completed": "Görev Tamamlandı",
  "Task Failed": "Görev Başarısız Oldu",
  "Terminal Bell": "Terminal Zili",
  "Terminal Command Failed": "Terminal Komutu Başarısız Oldu",
  "Terminal Command Succeeded": "Terminal Komutu Başarılı Oldu",
  "Terminal Quick Fix": "Terminal Hızlı Düzeltmesi",
  "Voice Recording Started": "Ses Kaydı Başladı",
  "Voice Recording Stopped": "Ses Kaydı Durdu",
  "Underline Links": "Bağlantıların Altını Çiz",
  "Verbose Chat Progress Updates": "Ayrıntılı Sohbet İlerleme Güncellemeleri",
  "Debug": "Hata Ayıkla",
  "Diff Editor": "Fark Düzenleyici",
  "Diff Editor Active": "Fark Düzenleyici Etkin",
  "Empty Editor Hint": "Boş Düzenleyici İpucu",
  "Inline Chat": "Satır İçi Sohbet",
  "Inline Completions": "Satır İçi Tamamlamalar",
  "Keybindings Editor": "Tuş Atamaları Düzenleyici",
  "Notebook": "Not Defteri",
  "Notification": "Bildirim",
  "Panel Chat": "Panel Sohbeti",
  "Repl Editor": "Repl Düzenleyici",
  "Source Control": "Kaynak Denetimi",
  "Terminal": "Terminal",
  "Terminal Chat Output": "Terminal Sohbet Çıktısı",
  "Walkthrough": "Tanıtım",
  "Auto Synthesize": "Otomatik Sentezle",
  "Ignore Code Blocks": "Kod Bloklarını Yoksay",
  "Speech Language": "Konuşma Dili",
  "Speech Timeout": "Konuşma Zaman Aşımı",
  "Window Title Optimized": "Pencere Başlığı Optimize Edildi",
  "Max Requests": "Maksimum Requests",
  "Collapsed Tools": "Daraltılmış Araçlar",
  "Allow Anonymous Access": "Anonim Erişime İzin Ver",
  "Show File Changes": "Dosya Değişikliklerini Göster",
  "Disable AI Features": "Yapay Zeka Özelliklerini Devre Dışı Bırak",
  "Edit Requests": "Düzenle Requests",
  "Auto Accept Delay": "Otomatik Kabul Gecikmesi",
  "Confirm Edit Request Removal": "Onayla Düzenle İstek Kaldırma",
  "Confirm Edit Request Retry": "Onayla Düzenle İstek Yeniden Dene",
  "Suggested Context": "Önerilen Bağlam",
  "Fix": "Düzelt",
  "Notify Window On Confirmation": "Onaylandığında Pencereyi Bildir",
  "Render Related Files": "İlgili Dosyaları Göster",
  "Attach CSS": "CSS Ekle",
  "Attach Images": "Görüntüleri Ekle",
  "Sku": "SKU",
  "Description Field": "Açıklama Alan",
  "Write Only": "Yalnızca Yaz",
  "Auto Approve": "Otomatik Onaylama",
  "Auto Reply To Prompts": "Komut İstemlerini Otomatik Yanıtla",
  "Block Detected File Writes": "Algılanan Dosya Yazma İşlemlerini Engelle",
  "Enable Auto Approve": "Otomatik Onaylamayı Etkinleştir",
  "Ignore Default Auto Approve Rules": "Varsayılan Otomatik Onay Kurallarını Yoksay",
  "Output Location": "Çıktı Konumu",
  "Shell Integration Timeout": "Kabuk Tümleştirmesi Zaman Aşımı",
  "Linux": "Linux",
  "Osx": "OS X",
  "Windows": "Windows",
  "Restore Input": "Girdiyi Geri Yükle",
  "Collapse On Resolve": "Çözümlendiğinde Daralt",
  "Max Height": "Maksimum Yüksekliği",
  "Open Panel": "Paneli Aç",
  "Open View": "Görünümü Aç",
  "Confirm On Collapse": "Daraltırken Onayla",
  "Use Relative Time": "Göreceli Zaman Kullan",
  "Visible": "Görünür",
  "Allow Breakpoints Everywhere": "Her Yerde Kesme Noktalarına İzin Ver",
  "Auto Expand Lazy Variables": "Tembel Değişkenleri Otomatik Genişlet",
  "Close Readonly Tabs On End": "Sonlandığında Salt Okunur Sekmeleri Kapat",
  "Confirm On Exit": "Çıkışta Onayla",
  "Close On End": "Sonlandığında Kapat",
  "Collapse Identical Lines": "Özdeş Satırları Daralt",
  "History Suggestions": "Geçmişi Öneriler",
  "Maximum Lines": "Maksimum Satırlar",
  "Show Source Code": "Kaynak Kodunu Göster",
  "Enable Status Bar Color": "Durum Çubuğu Rengini Etkinleştir",
  "Focus Editor On Break": "Duraklamada Düzenleyiciye Odaklan",
  "Focus Window On Break": "Duraklamada Pencereye Odaklan",
  "Gutter Middle Click Action": "Kenar Boşluğunda Orta Tuş Eylemi",
  "Hide Launcher While Debugging": "Hata Ayıklarken Başlatıcıyı Gizle",
  "Hide Slow Pre Launch Warning": "Yavaş Ön Başlatma Uyarısını Gizle",
  "Inline Values": "Satır İçi Değerler",
  "On Task Errors": "Görev Hatalarında",
  "Open Debug": "Hata Ayıklamayı Aç",
  "Open Explorer On End": "Sonlandığında Gezgini Aç",
  "Save Before Start": "Başlatmadan Önce Kaydet",
  "Show Breakpoints In Overview Ruler": "Genel Bakış Cetvelinde Kesme Noktalarını Göster",
  "Show In Status Bar": "Durum Çubuğunda Göster",
  "Show Inline Breakpoint Candidates": "Satır İçi Kesme Noktası Adaylarını Göster",
  "Show Sub Sessions In Tool Bar": "Araç Çubuğunda Alt Oturumları Göster",
  "Show Variable Types": "Değişken Türlerini Göster",
  "Clear Before Reusing": "Yeniden Kullanmadan Önce Terminali Temizle",
  "Tool Bar Location": "Araç Çubuğu Konumu",
  "Diff Algorithm": "Fark Algoritma",
  "Show Empty Decorations": "Boş Süslemeleri Göster",
  "Show Moves": "Kod Taşımalarını Göster",
  "Use True Inline View": "Gerçek Satır İçi Görünümü Kullan",
  "Context Line Count": "Bağlam Satır Sayısı",
  "Minimum Line Count": "Minimum Satır Sayısı",
  "Reveal Line Count": "Gösterilecek Satır Sayısı",
  "Ignore Trim Whitespace": "Kırpılan Boşlukları Yoksay",
  "Max Computation Time": "Maksimum Hesaplama Süresi",
  "Max File Size": "Maksimum Dosya Boyutu",
  "Render Gutter Menu": "Kenar Boşluğu Menüsünü Göster",
  "Render Indicators": "Göstergeleri Göster",
  "Render Margin Revert Icon": "Kenar Boşluğu Geri Döndürme Simgesini Göster",
  "Render Side By Side": "Yan Yana Göster",
  "Render Side By Side Inline Breakpoint": "Satır İçi Kesme Noktasını Yan Yana Göster",
  "Use Inline View When Space Is Limited": "Alan Sınırlı Olduğunda Satır İçi Görünümü Kullan",
  "Css": "Css",
  "Ini": "Ini",
  "Regex": "Regex",
  "Typescript": "TypeScript",
  "History": "Geçmişi",
  "Loop": "Loop",
  "Multiple": "Çoklu",
  "Bracket Pairs": "Ayraç Çiftleri",
  "Above": "Yukarıda",
  "Delay": "Gecikme",
  "Sticky": "Sabit",
  "Indent Size": "Girinti Boyutu",
  "Maximum Length": "Maksimum Uzunluğu",
  "Allow Code Shifting": "Kod Kaydırmaya İzin Ver",
  "Show Collapsed": "Daraltılmış Olarak Göster",
  "Show Long Distance Hint": "Uzun Mesafe İpucunu Göster",
  "Empty Response Information": "Boş Yanıt Bilgi",
  "Show On Suggest Conflict": "Öneri Çakışmasında Göster",
  "Suppress Inline Suggestions": "Satır İçi Önerileri Gizle",
  "Min Show Delay": "Minimum Göster Gecikme",
  "Show Toolbar": "Araç Çubuğunu Göster",
  "Suppress In Snippet Mode": "Kod Parçacığı Modunda Gizle",
  "Suppress Suggestions": "Önerileri Gizle",
  "Syntax Highlighting Enabled": "Sözdizimi Vurgulaması Etkin",
  "Trigger Command On Provider Change": "Sağlayıcı Değiştiğinde Komutu Tetikle",
  "Brackets": "Ayraçlar",
  "Large File Optimizations": "Büyük Dosya İyileştirmeler",
  "Max Tokenization Line Length": "Maksimum Belirteç Ayırma Satır Uzunluğu",
  "Autohide": "Otomatik Gizleme",
  "Mark Section Header Regex": "Bölüm Başlığı İşareti Normal İfadesi (Regex)",
  "Max Column": "Maksimum Sütun",
  "Render Characters": "İşle Karakterler",
  "Scale": "Ölçek",
  "Section Header Font Size": "Bölüm Başlık Yazı Tipi Boyutu",
  "Section Header Letter Spacing": "Bölüm Başlık Harf Boşluklandırma",
  "Show Mark Section Headers": "Bölüm Başlığı İşaretlerini Göster",
  "Show Region Section Headers": "Bölge Başlıklarını Göster",
  "Show Slider": "Kaydırıcıyı Göster",
  "Side": "Yan",
  "Size": "Boyutu",
  "Bottom": "Alt",
  "Top": "Üst",
  "Cycle": "Cycle",
  "Show Paste Selector": "Yapıştırma Seçicisini Göster",
  "Horizontal": "Yatay",
  "Horizontal Scrollbar Size": "Yatay Kaydırma Çubuğu Boyutu",
  "Ignore Horizontal Scrollbar In Content Height": "İçerik Yüksekliğinde Yatay Kaydırma Çubuğunu Yoksay",
  "Scroll By Page": "Sayfa Sayfa Kaydır",
  "Vertical": "Dikey",
  "Vertical Scrollbar Size": "Dikey Kaydırma Çubuğu Boyutu",
  "Select Leading And Trailing Whitespace": "Baştaki ve Sondaki Boşlukları Seç",
  "Select Subwords": "Alt Sözcükleri Seç",
  "Stable Peek": "Kararlı Gözat",
  "Scroll With Editor": "Düzenleyici ile Birlikte Kaydır",
  "Filter Graceful": "Filtrele Kademeli",
  "Filtered Types": "Filtrelenen Türler",
  "Insert Mode": "Insert Mod",
  "Locality Bonus": "Yerellik Bonus",
  "Match On Word Start Only": "Eşleşme Üzerinde Sözcük Başlat Yalnızca",
  "Max Visible Suggestions": "Maksimum Görünür Öneriler",
  "Preview": "Önizleme",
  "Selection Mode": "Seçim Mod",
  "Share Suggest Selections": "Paylaş Öner Seçimler",
  "Show Classes": "Sınıfları Göster",
  "Show Colors": "Renkleri Göster",
  "Show Constants": "Sabitleri Göster",
  "Show Constructors": "Yapıcıları Göster",
  "Show Customcolors": "Özel Renkleri Göster",
  "Show Enum Members": "Numaralandırma Üyelerini Göster",
  "Show Enums": "Numaralandırmaları Göster",
  "Show Events": "Olayları Göster",
  "Show Fields": "Alanları Göster",
  "Show Files": "Dosyaları Göster",
  "Show Folders": "Klasörleri Göster",
  "Show Functions": "İşlevleri Göster",
  "Show Icons": "Simgeleri Göster",
  "Show Inline Details": "Satır İçi Ayrıntıları Göster",
  "Show Interfaces": "Arayüzleri Göster",
  "Show Issues": "Sorunları Göster",
  "Show Keywords": "Anahtar Sözcükleri Göster",
  "Show Methods": "Yöntemleri Göster",
  "Show Modules": "Modülleri Göster",
  "Show Operators": "İşleçleri Göster",
  "Show Properties": "Özellikleri Göster",
  "Show References": "Başvuruları Göster",
  "Show Snippets": "Kod Parçacıklarını Göster",
  "Show Status Bar": "Durum Çubuğunu Göster",
  "Show Structs": "Yapıları Göster",
  "Show Type Parameters": "Tür Parametrelerini Göster",
  "Show Units": "Birimleri Göster",
  "Show Users": "Kullanıcıları Göster",
  "Show Values": "Değerleri Göster",
  "Show Variables": "Değişkenleri Göster",
  "Show Words": "Sözcükleri Göster",
  "Snippets Prevent Quick Suggestions": "Kod Parçacıkları Hızlı Önerileri Engellesin",
  "Trim Auto Whitespace": "Otomatik Boşlukları Kırp",
  "Auto Open Dropped File": "Bırakılan Dosyayı Otomatik Aç",
  "Auto Reveal": "Otomatik Göster",
  "Auto Reveal Exclude": "Otomatik Göstermeden Dışlananlar",
  "Compact Folders": "Kompakt Klasörler",
  "Confirm Drag And Drop": "Sürükle ve Bırakı Onayla",
  "Confirm Paste Native": "Yerel Yapıştırmayı Onayla",
  "Confirm Undo": "Geri Almayı Onayla",
  "Copy Path Separator": "Yol Ayırıcısını Kopyala",
  "Copy Relative Path Separator": "Göreceli Yol Ayırıcısını Kopyala",
  "Badges": "Rozetler",
  "Colors": "Renkler",
  "Enable Drag And Drop": "Sürükle ve Bırakı Etkinleştir",
  "Enable Undo": "Geri Almayı Etkinleştir",
  "Exclude Git Ignore": ".gitignore Dosyasına Göre Dışla",
  "Expand Single Folder Workspaces": "Tek Klasörlü Çalışma Alanlarını Genişlet",
  "Expand": "Genişlet",
  "Patterns": "Desenler",
  "Incremental Naming": "Artımlı Adlandırma",
  "Min Visible": "Minimum Görünür",
  "Sort Order": "Sıralama Düzeni",
  "Sort Order Lexicographic Options": "Sözlükbilimsel Sıralama Seçenekleri",
  "Sort Order Reverse": "Ters Sıralama Düzeni",
  "Auto Check Updates": "Güncellemeleri Otomatik Denetle",
  "Auto Update": "Otomatik Güncelle",
  "Close Extension Details On View Change": "Görünüm Değiştiğinde Uzantı Ayrıntılarını Kapat",
  "Confirmed Uri Handler Extension Ids": "Onaylandı URI İşleyici Uzantı Ids",
  "Affinity": "Benzerlik",
  "Deferred Startup Finished Activation": "Ertelenmiş Başlangıç Tamamlama Etkinleştirmesi",
  "Issue Quick Access": "Sorun Hızlı Erişimi",
  "Ignore Recommendations": "Önerileri Yoksay",
  "Show Recommendations Only On Demand": "Önerileri Yalnızca İstek Üzerine Göster",
  "Support Node Global Navigator": "Node Global Gezginini Destekle",
  "Support Virtual Workspaces": "Sanal Çalışma Alanlarını Destekle",
  "Web Worker": "Web Çalışanı",
  "Auto Guess Encoding": "Kodlamayı Otomatik Tahmin Et",
  "Auto Save When No Errors": "Hata Olmadığında Otomatik Kaydet",
  "Auto Save Workspace Files Only": "Yalnızca Çalışma Alanı Dosyalarını Otomatik Kaydet",
  "Candidate Guess Encodings": "Aday Kodlama Tahminleri",
  "Default Language": "Varsayılan Dil",
  "Default Path": "Varsayılan Yol",
  "Enable Trash": "Çöp Kutusunu Etkinleştir",
  "Encoding": "Kodlama",
  "Eol": "Satır Sonu",
  "Insert Final Newline": "Son Satır Sonu Ekle",
  "Timeout": "Zaman Aşımı",
  "Restore Undo Stack": "Geri Alma Geçmişini Geri Yükle",
  "Save Conflict Resolution": "Çakışma Çözümünü Kaydet",
  "Enable": "Etkinleştir",
  "Trim Final Newlines": "Sondaki Yeni Satırları Kırp",
  "Trim Trailing Whitespace": "Sondaki Boşlukları Kırp",
  "Trim Trailing Whitespace In Regex And Strings": "Regex ve Dizgilerdeki Sondaki Boşlukları Kırp",
  "Watcher Exclude": "İzleyiciden Dışlananlar",
  "Watcher Include": "İzleyiciye Dahil Edilenler",
  "Clone": "Klonla",
  "Accessible Diff View": "Erişilebilir Fark Görünümü",
  "Enable V2": "V2'yi Etkinleştir",
  "Finish On Type": "Yazma Tamamlandığında Bitir",
  "Hold To Speech": "Konuşmak İçin Basılı Tut",
  "Notebook Agent": "Not Defteri Ajanı",
  "Toggle Inline": "Satır İçini Aç/Kapat",
  "Ignore Metadata": "Meta Verileri Yoksay",
  "Ignore Outputs": "Çıktıları Yoksay",
  "Allow Navigate To Surrounding Cells": "Çevreleyen Hücrelerde Gezinmeye İzin Ver",
  "Always Show Actions": "Eylemleri Her Zaman Göster",
  "Always Show Repositories": "Depoları Her Zaman Göster",
  "Count Badge": "Sayısı Rozet",
  "Default View Mode": "Varsayılan Görünüm Mod",
  "Default View Sort Key": "Varsayılan Görünüm Sırala Anahtar",
  "Diff Decorations": "Fark Süslemeler",
  "Diff Decorations Gutter Action": "Fark Süslemeler Kenar Boşluğu Eylem",
  "Diff Decorations Gutter Pattern": "Fark Süslemeler Kenar Boşluğu Desen",
  "Diff Decorations Gutter Visibility": "Fark Süslemeler Kenar Boşluğu Görünürlük",
  "Diff Decorations Gutter Width": "Fark Süslemeler Kenar Boşluğu Genişliği",
  "Diff Decorations Ignore Trim Whitespace": "Fark Süslemelerinde Kırpılan Boşlukları Yoksay",
  "Page On Scroll": "Sayfa Üzerinde Kaydır",
  "Page Size": "Sayfa Boyutu",
  "Show Incoming Changes": "Gelen Değişiklikleri Göster",
  "Show Outgoing Changes": "Giden Değişiklikleri Göster",
  "Input Font Family": "Girdi Yazı Tipi Ailesi",
  "Input Font Size": "Girdi Yazı Tipi Boyutu",
  "Input Max Line Count": "Girdi Maksimum Satır Sayısı",
  "Input Min Line Count": "Girdi Minimum Satır Sayısı",
  "Provider Count Badge": "Sağlayıcı Sayısı Rozet",
  "Explorer": "Gezgin",
  "Show Action Button": "Eylem Düğmesini Göster",
  "Show Input Action Button": "Girdi Eylem Düğmesini Göster",
  "Default": "Varsayılan",
  "Keyboard Options": "Klavye Seçenekleri",
  "Keyboard Overlay Timeout": "Klavye Katmanı Zaman Aşımı",
  "Mouse Indicator Color": "Fare Gösterge Rengi",
  "Mouse Indicator Size": "Fare Gösterge Boyutu",
  "Vertical Offset": "Dikey Uzaklığı",
  "Actions Position": "Eylemler Konumu",
  "Collapse Results": "Sonuçları Daralt",
  "Closed Notebook Rich Content Results": "Kapatılan Not Defteri Zengin İçerik Sonuçları",
  "Follow Symlinks": "Sembolik Bağlantıları Takip Et",
  "Location": "Location",
  "Maintain File Search Cache": "Dosya Arama Önbelleğini Koru",
  "Max Results": "Maksimum Sonuç Sayısı",
  "Preserve Input": "Girdiyi Koru",
  "Filter Sort Order": "Filtre Sıralama Düzeni",
  "Include History": "Geçmişi Dahil Et",
  "Include Symbols": "Sembolleri Dahil Et",
  "Max Threads": "Maksimum İş Parçacıkları",
  "Default Number Of Context Lines": "Varsayılan Bağlam Satırı Sayısı",
  "Double Click Behaviour": "Çift Tıklama Davranışı",
  "Focus Results On Search": "Arama Yapıldığında Sonuçlara Odaklan",
  "Reuse Prior Search Configuration": "Önceki Arama Yapılandırmasını Yeniden Kullan",
  "Single Click Behaviour": "Tek Tıklama Davranışı",
  "Search On Type": "Yazarken Ara",
  "Search On Type Debounce Period": "Yazarken Arama Gecikme Süresi",
  "Keyword Suggestions": "Anahtar Sözcük Öneriler",
  "Semantic Search Behavior": "Anlamsal Arama Davranışı",
  "Seed On Focus": "Odaklandığında Başlat",
  "Seed With Nearest Word": "En Yakın Sözcükle Başlat",
  "Show Line Numbers": "Satır Numaralarını Göster",
  "Smart Case": "Büyük/Küçük Harfe Duyarlı (Akıllı)",
  "Use Global Ignore Files": "Genel Yoksayma Dosyalarını Kullan",
  "Use Ignore Files": "Yoksayma Dosyalarını Kullan",
  "Use PCRE2": "PCRE2 Kullan",
  "Use Parent Ignore Files": "Üst Dizin Yoksayma Dosyalarını Kullan",
  "Use Replace Preview": "Değiştirme Önizlemesini Kullan",
  "Use Ripgrep": "Ripgrep Kullan",
  "Allowed UNC Hosts": "İzin Verilen UNC Ana Bilgisayarları",
  "Prompt For Local File Protocol Handling": "Yerel Dosya Protokolü İçin Sor",
  "Prompt For Remote File Protocol Handling": "Uzak Dosya Protokolü İçin Sor",
  "Restrict UNC Access": "UNC Erişimini Kısıtla",
  "Enable Crash Reporter": "Etkinleştir Crash Reporter",
  "Ansi Black": "Ansi Siyah",
  "Ansi Blue": "Ansi Mavi",
  "Ansi Bright Black": "Ansi Parlak Siyah",
  "Ansi Bright Blue": "Ansi Parlak Mavi",
  "Ansi Bright Cyan": "Ansi Parlak Camgöbeği",
  "Ansi Bright Green": "Ansi Parlak Yeşil",
  "Ansi Bright Magenta": "Ansi Parlak Eflatun",
  "Ansi Bright Red": "Ansi Parlak Kırmızı",
  "Ansi Bright White": "Ansi Parlak Beyaz",
  "Ansi Bright Yellow": "Ansi Parlak Sarı",
  "Ansi Cyan": "Ansi Camgöbeği",
  "Ansi Green": "Ansi Yeşil",
  "Ansi Magenta": "Ansi Eflatun",
  "Ansi Red": "Ansi Kırmızı",
  "Ansi White": "Ansi Beyaz",
  "Ansi Yellow": "Ansi Sarı",
  "Explorer Kind": "Gezgin Türü",
  "Linux Exec": "Linux Çalıştır",
  "Osx Exec": "OS X Çalıştır",
  "Windows Exec": "Windows Yürütülebilir Dosyası",
  "Accessible View Focus On Command Execution": "Accessible Görünüm Odaklan Üzerinde Komut Yürütme",
  "Accessible View Preserve Cursor Position": "Accessible Görünüm Koru İmleç Konumu",
  "Allow Chords": "Akor Kısayollarına İzin Ver",
  "Allow Mnemonics": "Kısayol Harflerine İzin Ver",
  "Allowed Link Schemes": "İzin Verilen Bağlantı Şemaları",
  "Alt Click Moves Cursor": "Alt + Tıklama İmleci Taşısın",
  "Auto Replies": "Otomatik Yanıtlar",
  "Bell Duration": "Zil Süre",
  "Commands To Skip Shell": "Kabuğu Atlayacak Komutlar",
  "Confirm On Kill": "Sonlandırırken Onayla",
  "Copy On Selection": "Seçildiğinde Kopyala",
  "Cursor Style Inactive": "Etkin Olmayan İmleç Stili",
  "Custom Glyphs": "Özel Simgeler",
  "Cwd": "Çalışma Dizini",
  "Default Location": "Varsayılan Konum",
  "Detect Locale": "Yerel Ayarı Algıla",
  "Dev Mode": "Geliştirici Mod",
  "Latency": "Gecikme Süresi",
  "Startup Delay": "Başlangıç Gecikmesi",
  "Draw Bold Text In Bright Colors": "Kalın Metni Parlak Renklerle Çiz",
  "Enable Bell": "Zili Etkinleştir",
  "Enable File Links": "Dosya Bağlantılarını Etkinleştir",
  "Enable Images": "Görüntüleri Etkinleştir",
  "Enable Multi Line Paste Warning": "Çok Satırlı Yapıştırma Uyarısını Etkinleştir",
  "Enable Persistent Sessions": "Kalıcı Oturumları Etkinleştir",
  "Enable Visual Bell": "Görsel Zili Etkinleştir",
  "Environment Changes Relaunch": "Ortam Değişikliklerinde Yeniden Başlat",
  "Focus After Run": "Çalıştırdıktan Sonra Odaklan",
  "Fallback Ligatures": "Yedek Bitiştirmeler",
  "Feature Settings": "Özellik Ayarlar",
  "Font Weight Bold": "Yazı Tipi Kalınlık Kalın",
  "Gpu Acceleration": "Gpu Acceleration",
  "Hide On Last Closed": "Son Kapatıldığında Gizle",
  "Hide On Startup": "Başlangıçta Gizle",
  "Ignore Bracketed Paste Mode": "Köşeli Parantezli Yapıştırma Modunu Yoksay",
  "Ignore Process Names": "Yoksayılacak İşlem Adları",
  "Inherit Env": "Ortam Değişkenlerini Devral",
  "Initial Hint": "İlk İpucu",
  "Local Echo Enabled": "Yerel Yankı Etkin",
  "Local Echo Exclude Programs": "Yerel Yankı Dışla Programlar",
  "Local Echo Latency Threshold": "Yerel Yankı Gecikme Süresi Eşik",
  "Local Echo Style": "Yerel Yankı Stil",
  "Mac Option Click Forces Selection": "Mac Option + Tıklama Seçimi Zorlasın",
  "Mac Option Is Meta": "Mac Option Tuşu Meta Olsun",
  "Middle Click Behavior": "Orta Tıklama Davranışı",
  "Minimum Contrast Ratio": "Minimum Kontrast Oran",
  "Persistent Session Revive Process": "Kalıcı Oturum Canlandır İşlem",
  "Persistent Session Scrollback": "Kalıcı Oturum Geri Kaydırma",
  "Rescale Overlapping Glyphs": "Yeniden Ölçekle Üst Üste Binen Simgeler",
  "Right Click Behavior": "Sağ Tıklama Davranışı",
  "Scrollback": "Geri Kaydırma",
  "Send Keybindings To Shell": "Tuş Atamalarını Kabuğa Gönder",
  "Decorations Enabled": "Süslemeler Etkin",
  "Environment Reporting": "Ortam Raporlama",
  "Quick Fix Enabled": "Hızlı Düzelt Etkin",
  "Show Command Guide": "Komut Kılavuzunu Göster",
  "Show Exit Alert": "Çıkış Uyarısını Göster",
  "Show Link Hover": "Bağlantı Üzerine Gelindiğinde İpucunu Göster",
  "Split Cwd": "Bölünmüş Çalışma Dizini",
  "Cd Path": "Cd Yol",
  "Inline Suggestion": "Satır İçi Öneri",
  "Insert Trailing Space": "Insert Sondaki Boşluk",
  "Providers": "Sağlayıcılar",
  "Run On Enter": "Çalıştır Üzerinde Enter",
  "Up Arrow Navigates History": "Yukarı Ok Geçmişte Gezinsin",
  "Windows Executable Extensions": "Windows Yürütülebilir Dosya Uzantıları",
  "Tab Stop Width": "Sekme Durağı Genişliği",
  "Default Color": "Varsayılan Renk",
  "Default Icon": "Varsayılan Simge",
  "Description": "Açıklama",
  "Enable Animation": "Etkinleştir Animasyon",
  "Focus Mode": "Odaklan Mod",
  "Hide Condition": "Gizle Koşul",
  "Separator": "Separator",
  "Show Actions": "Eylemleri Göster",
  "Show Active Terminal": "Etkin Terminali Göster",
  "Title": "Başlık",
  "Unicode Version": "Unicode Sürümü",
  "Use Wsl Profiles": "WSL Profillerini Kullan",
  "Windows Enable Conpty": "Windows ConPTY'yi Etkinleştir",
  "Windows Use Conpty Dll": "Windows ConPTY DLL Kullan",
  "Send Selection To Agent": "Seçimi Ajana Gönder",
  "Source Control Repositories Kind": "Kaynak Denetimi Depoları Türü",
  "Always Reveal Test On State Change": "Durum Değiştiğinde Testi Her Zaman Göster",
  "Automatically Open Peek View": "Gözat Görünümünü Otomatik Aç",
  "Automatically Open Peek View During Auto Run": "Otomatik Çalıştırma Sırasında Gözat Görünümünü Otomatik Aç",
  "Automatically Open Test Results": "Test Sonuçlarını Otomatik Olarak Aç",
  "Coverage Bar Thresholds": "Kapsam Çubuğu Eşikler",
  "Coverage Toolbar Enabled": "Kapsam Araç Çubuğu Etkin",
  "Default Gutter Click Action": "Varsayılan Kenar Boşluğu Tıklama Eylem",
  "Displayed Coverage Percent": "Displayed Kapsam Yüzde",
  "Follow Running Test": "Çalışan Testi Takip Et",
  "Gutter Enabled": "Kenar Boşluğu Etkin",
  "Layout": "Layout",
  "Save Before Test": "Testten Önce Kaydet",
  "Show All Messages": "Tüm İletileri Göster",
  "Show Coverage In Explorer": "Kapsamı Gezginde Göster",
  "Channel": "Channel",
  "Enable Windows Background Updates": "Windows Arka Plan Güncellemelerini Etkinleştir",
  "Mode": "Mod",
  "Border": "Kenarlık",
  "Click Through Inactive": "Etkin Olmayan Pencereye Tıklama Geçişi",
  "Close When Empty": "Boş Olduğunda Kapat",
  "Confirm Before Close": "Kapatmadan Önce Onayla",
  "Confirm Save Untitled Workspace": "Başlıksız Çalışma Alanını Kaydederken Onayla",
  "Controls Style": "Denetim Stili",
  "Custom Menu Bar Alt Focus": "Özel Menü Çubuğuna Alt ile Odaklanma",
  "Custom Title Bar Visibility": "Özel Başlık Çubuğu Görünürlüğü",
  "Editor Tab Height": "Düzenleyici Sekme Yüksekliği",
  "Dialog Style": "İletişim Kutusu Stili",
  "Double Click Icon To Close": "Kapatmak İçin Simgeye Çift Tıkla",
  "Enable Menu Bar Mnemonics": "Menü Çubuğu Kısayol Harflerini Etkinleştir",
  "Menu Bar Visibility": "Menü Çubuğu Görünürlüğü",
  "Menu Style": "Menü Stili",
  "Native Full Screen": "Yerel Tam Ekran",
  "Native Tabs": "Yerel Sekmeler",
  "New Window Dimensions": "Yeni Pencere Boyutları",
  "New Window Profile": "Yeni Pencere Profili",
  "Open Files In New Window": "Dosyaları Yeni Pencerede Aç",
  "Open Folders In New Window": "Klasörleri Yeni Pencerede Aç",
  "Open Without Arguments In New Window": "Bağımsız Değişken Olmadan Yeni Pencerede Aç",
  "Restore Fullscreen": "Tam Ekranı Geri Yükle",
  "Restore Windows": "Pencereleri Geri Yükle",
  "Title Bar Style": "Başlık Çubuğu Stili",
  "Title Separator": "Başlık Ayırıcısı",
  "Zoom Per Window": "Pencere Başına Yakınlaştırma",
  "Focus": "Odaklan",
  "Split": "Böl",
  "Switch Terminal": "Terminale Geçiş Yap",
  "Icon Click Behavior": "Simge Tıklama Davranış",
  "Auto Resume": "Otomatik Sürdür",
  "Continue On": "Devam Et Üzerinde",
  "Ask Chat Location": "Sohbet Konumunu Sor",
  "Enable Natural Language Search": "Etkinleştir Doğal Dil Ara",
  "Suggest Commands": "Komutları Öner",
  "Show Ask In Chat": "Komut Paletinde Sohbetten Sor Seçeneğini Göster",
  "Always Show Editor Actions": "Düzenleyici Eylemlerini Her Zaman Göster",
  "Auto Lock Groups": "Grupları Otomatik Kilitle",
  "Centered Layout Auto Resize": "Ortalanmış Düzeni Otomatik Yeniden Boyutlandır",
  "Centered Layout Fixed Width": "Ortalanmış Düzen Sabit Genişliği",
  "Close Empty Groups": "Boş Grupları Kapat",
  "Close On File Delete": "Dosya Silindiğinde Kapat",
  "Default Binary Editor": "Varsayılan İkili Düzenleyici",
  "Double Click Tab To Toggle Editor Group Sizes": "Düzenleyici Grup Boyutunu Değiştirmek İçin Sekmeye Çift Tıkla",
  "Drag To Open Window": "Pencere Açmak İçin Sürükle",
  "Editor Actions Location": "Düzenleyici Eylemleri Konumu",
  "Hint": "İpucu",
  "Enable Preview From Code Navigation": "Kodda Gezinirken Önizlemeyi Etkinleştir",
  "Enable Preview From Quick Open": "Hızlı Aç'tan Önizlemeyi Etkinleştir",
  "Focus Recent Editor After Close": "Kapattıktan Sonra Son Düzenleyiciye Odaklan",
  "Highlight Modified Tabs": "Değiştirilen Sekmeleri Vurgula",
  "History Based Language Detection": "Geçmişe Dayalı Dil Algılama",
  "Label Format": "Etiket Biçimi",
  "Language Detection": "Dil Algılama",
  "Language Detection Hints": "Dil Algılama İpuçları",
  "Exclude Dirty": "Dışla Kaydedilmemiş",
  "Per Editor Group": "Başına Düzenleyici Grup",
  "Value": "Değer",
  "Mouse Back Forward To Navigate": "Gezinmek İçin Fare Geri/İleri Düğmelerini Kullan",
  "Navigation Scope": "Gezinme Kapsam",
  "Open Positioning": "Aç Konumlandırma",
  "Open Side By Side Direction": "Aç Yan Göre Yan Yön",
  "Pinned Tab Sizing": "Sabitlenmiş Sekme Boyutlandırma",
  "Pinned Tabs On Separate Row": "Sabitlenmiş Sekmeler Üzerinde Ayrı Satır",
  "Prefer History Based Language Detection": "Geçmişe Dayalı Dil Algılamayı Tercih Et",
  "Prevent Pinned Editor Close": "Sabitlenmiş Düzenleyicinin Kapatılmasını Önle",
  "Restore View State": "Görünüm Durumunu Geri Yükle",
  "Reveal If Open": "Açıksa Göster",
  "Scroll To Switch Tabs": "Sekmeler Arasında Geçiş Yapmak İçin Kaydır",
  "Shared View State": "Paylaşılan Görünüm Durumu",
  "Show Tab Index": "Sekme İndeksini Göster",
  "Show Tabs": "Sekmeleri Göster",
  "Split In Group Layout": "Grup Düzeninde Böl",
  "Split On Drag And Drop": "Sürükleyip Bırakırken Böl",
  "Split Sizing": "Bölme Boyutlandırması",
  "Swipe To Navigate": "Gezinmek İçin Kaydır",
  "Tab Action Close Visibility": "Sekme Kapatma Eylemi Görünürlüğü",
  "Tab Action Location": "Sekme Eylemi Konumu",
  "Tab Action Unpin Visibility": "Sekme Sabitlemeyi Kaldırma Görünürlüğü",
  "Tab Sizing": "Sekme Boyutlandırması",
  "Tab Sizing Fixed Max Width": "Sabit Sekme Maksimum Genişliği",
  "Tab Sizing Fixed Min Width": "Sabit Sekme Minimum Genişliği",
  "Title Scrollbar Sizing": "Başlık Kaydırma Çubuğu Boyutlandırması",
  "Title Scrollbar Visibility": "Başlık Kaydırma Çubuğu Görünürlüğü",
  "Wrap Tabs": "Sekmeleri Kaydır",
  "Editor Associations": "Düzenleyici İlişkilendirmeleri",
  "Editor Large File Confirmation": "Büyük Dosya İçin Düzenleyici Onayı",
  "Enable Experiments": "Deneyleri Etkinleştir",
  "Auto Store": "Otomatik Depola",
  "External Browser": "Harici Tarayıcı",
  "Font Aliasing": "Yazı Tipi Kenar Yumuşatma",
  "Type": "Tür",
  "Exclude": "Dışla",
  "Max File Entries": "Maksimum Dosya Girdiler",
  "Merge Window": "Pencereleri Birleştir",
  "Opens Maximized": "Ekranı Kaplamış Olarak Aç",
  "Output": "Çıktı",
  "Show Labels": "Etiketleri Göster",
  "Auxiliarybar": "İkincil Çubuk",
  "Panel": "Panel",
  "Sidebar": "Kenar Çubuğu",
  "Close On Focus Lost": "Odak Kaybolduğunda Kapat",
  "Reduce Motion": "Hareketi Azalt",
  "Show Extension Recommendations": "Uzantı Önerilerini Göster",
  "Hover Delay": "Üzerine Gelme Gecikme",
  "Default Visibility": "Varsayılan Görünürlük",
  "Editor": "Düzenleyici",
  "Open Default Keybindings": "Varsayılan Tuş Atamalarını Aç",
  "Open Default Settings": "Varsayılan Ayarları Aç",
  "Settings Search Toc Behavior": "Ayarlar Arama İçindekiler Tablosu Davranışı",
  "Show AI Search Toggle": "Yapay Zeka Araması Aç/Kapat Butonunu Göster",
  "Use Split JSON": "Bölünmüş JSON Kullan",
  "Startup Editor": "Başlangıç Düzenleyicisi",
  "Prompt In Trusted Workspace": "Güvenilen Çalışma Alanında Sor",
  "Always Show Header Actions": "Başlık Eylemlerini Her Zaman Göster",
  "Show Quietly": "Sessizce Göster",
  "Prefer Reduced Motion": "Azaltılmış Hareketi Tercih Et",
  "Open On Install": "Yüklendiğinde Aç",
  "Startup Prompt": "Başlangıç İstemi",
  "Banner": "Başlık Bandı",
  "Untrusted Files": "Güvenilmeyen Dosyalar",
  "Empty Window": "Boş Pencere",
  "Verify Signature": "İmzayı Doğrula",
  "Request Timeout": "İstek Zaman Aşımı",
  "Support Untrusted Workspaces": "Güvenilmeyen Çalışma Alanlarını Destekle",
  "Auto Restart": "Otomatik Yeniden Başlat",
  "Confirmed URI Handler Extension Ids": "Onaylanan URI İşleyici Uzantı Kimlikleri",
  "Trusted Publishers": "Güvenilen Yayıncılar",
  "Tools Contribution": "Araçlar Katkısı",
  "Featured": "Öne Çıkanlar",
  "Service URL": "Hizmet URL'si",
  "security.workspace.trust.enabled": "Etkin",
  "security.workspace.trust.startupPrompt": "Başlangıç İstemi",
  "security.workspace.trust.banner": "Başlık Bandı",
  "security.workspace.trust.untrustedFiles": "Güvenilmeyen Dosyalar",
  "security.workspace.trust.emptyWindow": "Boş Pencere",
  "security.allowedUNCHosts": "İzin Verilen UNC Ana Bilgisayarları",
  "security.restrictUNCAccess": "UNC Erişimini Kısıtla",
  "security.promptForLocalFileProtocolHandling": "Yerel Dosya Protokolü İçin Sor",
  "security.promptForRemoteFileProtocolHandling": "Uzak Dosya Protokolü İçin Sor",
  "extensions.verifySignature": "İmzayı Doğrula",
  "extensions.requestTimeout": "İstek Zaman Aşımı",
  "extensions.webWorker": "Web Çalışanı",
  "extensions.supportUntrustedWorkspaces": "Güvenilmeyen Çalışma Alanlarını Destekle",
  "extensions.supportVirtualWorkspaces": "Sanal Çalışma Alanlarını Destekle",
  "extensions.autoUpdate": "Otomatik Güncelle",
  "extensions.autoCheckUpdates": "Güncellemeleri Otomatik Denetle",
  "extensions.closeExtensionDetailsOnViewChange": "Görünüm Değiştiğinde Uzantı Ayrıntılarını Kapat",
  "extensions.autoRestart": "Otomatik Yeniden Başlat",
  "extensions.confirmedUriHandlerExtensionIds": "Onaylanan URI İşleyici Uzantı Kimlikleri",
  "extensions.ignoreRecommendations": "Önerileri Yoksay",
  "extensions.showRecommendationsOnlyOnDemand": "Önerileri Yalnızca İstek Üzerine Göster",
  "extensions.experimental.affinity": "Benzerlik",
  "extensions.experimental.deferredStartupFinishedActivation": "Ertelenmiş Başlangıç Tamamlama Etkinleştirmesi",
  "extensions.experimental.issueQuickAccess": "Sorun Hızlı Erişimi",
  "extensions.supportNodeGlobalNavigator": "Node Global Gezginini Destekle",
  "extensions.trustedPublishers": "Güvenilen Yayıncılar",
  "Semantic Token Color Customizations": "Anlamsal Belirteç Renk Özelleştirmeleri",
  "editor.semanticTokenColorCustomizations": "Anlamsal Belirteç Renk Özelleştirmeleri",
  "Allowed Characters": "İzin Verilen Karakterler",
  "editor.unicodeHighlight.allowedCharacters": "İzin Verilen Karakterler",
  "Allowed Locales": "İzin Verilen Yerel Ayarlar",
  "editor.unicodeHighlight.allowedLocales": "İzin Verilen Yerel Ayarlar",
  "Include Comments": "Yorumları Dahil Et",
  "editor.unicodeHighlight.includeComments": "Yorumları Dahil Et",
  "Include Strings": "Dizgileri Dahil Et",
  "editor.unicodeHighlight.includeStrings": "Dizgileri Dahil Et",
  "Non Basic ASCII": "Temel Olmayan ASCII",
  "editor.unicodeHighlight.nonBasicASCII": "Temel Olmayan ASCII",
  "editor.unicodeHighlight.ambiguousCharacters": "Belirsiz Karakterler",
  "editor.unicodeHighlight.invisibleCharacters": "Görünmez Karakterler",
  "editor.minimap.markSectionHeaderRegex": "Bölüm Başlığı İşareti Normal İfadesi (Regex)",
  "markSectionHeaderRegex": "Bölüm Başlığı İşareti Normal İfadesi (Regex)",
  "editor.scrollbar.ignoreHorizontalScrollbarInContentHeight": "İçerik Yüksekliğinde Yatay Kaydırma Çubuğunu Yoksay",
  "ignoreHorizontalScrollbarInContentHeight": "İçerik Yüksekliğinde Yatay Kaydırma Çubuğunu Yoksay",
  "editor.experimental.preferTreeSitter.regex": "Tree-sitter Normal İfadesi",
  "regex": "Regex",
  "diffEditor.ignoreTrimWhitespace": "Kırpılan Boşlukları Yoksay",
  "ignoreTrimWhitespace": "Kırpılan Boşlukları Yoksay",
  "http.proxyStrictSSL": "Katı SSL Proxy",
  "proxyStrictSSL": "Katı SSL Proxy",
  "Proxy Strict SSL": "Katı SSL Proxy",
  "http.experimental.networkInterfaceCheckInterval": "Ağ Arayüzü Denetim Aralığı",
  "networkInterfaceCheckInterval": "Ağ Arayüzü Denetim Aralığı",
  "Network Interface Check Interval": "Ağ Arayüzü Denetim Aralığı",
  "terminal.integrated.inheritEnv": "Ortam Değişkenlerini Devral",
  "inheritEnv": "Ortam Değişkenlerini Devral",
  "terminal.integrated.ignoreProcessNames": "Yoksayılacak İşlem Adları",
  "ignoreProcessNames": "Yoksayılacak İşlem Adları",
  "terminal.integrated.tabs.showActiveTerminal": "Etkin Terminali Göster",
  "showActiveTerminal": "Etkin Terminali Göster",
  "terminal.integrated.detectLocale": "Yerel Ayarı Algıla",
  "detectLocale": "Yerel Ayarı Algıla",
  "terminal.integrated.ignoreBracketedPasteMode": "Köşeli Parantezli Yapıştırma Modunu Yoksay",
  "ignoreBracketedPasteMode": "Köşeli Parantezli Yapıştırma Modunu Yoksay",
  "chat.tools.terminal.enableAutoApprove": "Otomatik Onaylamayı Etkinleştir",
  "enableAutoApprove": "Otomatik Onaylamayı Etkinleştir",
  "chat.tools.terminal.ignoreDefaultAutoApproveRules": "Varsayılan Otomatik Onay Kurallarını Yoksay",
  "ignoreDefaultAutoApproveRules": "Varsayılan Otomatik Onay Kurallarını Yoksay",
  "chat.tools.terminal.blockDetectedFileWrites": "Algılanan Dosya Yazma İşlemlerini Engelle",
  "blockDetectedFileWrites": "Algılanan Dosya Yazma İşlemlerini Engelle",
  "chat.tools.terminal.shellIntegrationTimeout": "Kabuk Tümleştirmesi Zaman Aşımı",
  "shellIntegrationTimeout": "Kabuk Tümleştirmesi Zaman Aşımı",
  "chat.tools.terminal.terminalProfile.linux": "Linux Terminal Profili",
  "linux": "Linux",
  "chat.tools.terminal.terminalProfile.osx": "OS X Terminal Profili",
  "osx": "OS X",
  "chat.tools.terminal.terminalProfile.windows": "Windows Terminal Profili",
  "windows": "Windows",
  "chat.tools.terminal.autoReplyToPrompts": "Komut İstemlerini Otomatik Yanıtla",
  "autoReplyToPrompts": "Komut İstemlerini Otomatik Yanıtla",
  "chat.tools.terminal.outputLocation": "Çıktı Konumu",
  "outputLocation": "Çıktı Konumu",
  "chat.agent.thinking.collapsedTools": "Daraltılmış Araçlar",
  "collapsedTools": "Daraltılmış Araçlar",
  "accessibility.verbosity.terminal": "Terminal",
  "terminal": "Terminal",
  "accessibility.verbosity.panelChat": "Panel Sohbeti",
  "panelChat": "Panel Sohbeti",
  "accessibility.verbosity.inlineChat": "Satır İçi Sohbet",
  "inlineChat": "Satır İçi Sohbet",
  "accessibility.verbosity.terminalChatOutput": "Terminal Sohbet Çıktısı",
  "terminalChatOutput": "Terminal Sohbet Çıktısı",
  "accessibility.verbosity.notebook": "Not Defteri",
  "notebook": "Not Defteri",
  "accessibility.signals.terminalCommandFailed": "Terminal Komutu Başarısız Oldu",
  "terminalCommandFailed": "Terminal Komutu Başarısız Oldu",
  "accessibility.signals.terminalCommandSucceeded": "Terminal Komutu Başarılı Oldu",
  "terminalCommandSucceeded": "Terminal Komutu Başarılı Oldu",
  "accessibility.signals.terminalQuickFix": "Terminal Hızlı Düzeltmesi",
  "terminalQuickFix": "Terminal Hızlı Düzeltmesi",
  "accessibility.signals.terminalBell": "Terminal Zili",
  "terminalBell": "Terminal Zili",
  "accessibility.signals.chatEditModifiedFile": "Sohbet Düzenlemesiyle Değiştirilen Dosya",
  "chatEditModifiedFile": "Sohbet Düzenlemesiyle Değiştirilen Dosya",
  "accessibility.signals.notebookCellCompleted": "Not Defteri Hücresi Tamamlandı",
  "notebookCellCompleted": "Not Defteri Hücresi Tamamlandı",
  "accessibility.signals.notebookCellFailed": "Not Defteri Hücresi Başarısız Oldu",
  "notebookCellFailed": "Not Defteri Hücresi Başarısız Oldu",
  "accessibility.signals.chatRequestSent": "Sohbet İsteği Gönderildi",
  "chatRequestSent": "Sohbet İsteği Gönderildi",
  "accessibility.signals.chatResponseReceived": "Sohbet Yanıtı Alındı",
  "chatResponseReceived": "Sohbet Yanıtı Alındı",
  "accessibility.signals.chatUserActionRequired": "Sohbette Kullanıcı Eylemi Gerekli",
  "chatUserActionRequired": "Sohbette Kullanıcı Eylemi Gerekli",
  "accessibility.openChatEditedFiles": "Sohbetle Düzenlenen Dosyaları Aç",
  "openChatEditedFiles": "Sohbetle Düzenlenen Dosyaları Aç",
  "accessibility.voice.ignoreCodeBlocks": "Kod Bloklarını Yoksay",
  "ignoreCodeBlocks": "Kod Bloklarını Yoksay",
  "workbench.editor.mouseBackForwardToNavigate": "Gezinmek İçin Fare Geri/İleri Düğmelerini Kullan",
  "mouseBackForwardToNavigate": "Gezinmek İçin Fare Geri/İleri Düğmelerini Kullan",
  "workbench.commandPalette.showAskInChat": "Komut Paletinde Sohbetten Sor Seçeneğini Göster",
  "showAskInChat": "Komut Paletinde Sohbetten Sor Seçeneğini Göster",
  "workbench.panel.showLabels": "Panel Etiketlerini Göster",
  "showLabels": "Etiketleri Göster",
  "workbench.panel.defaultLocation": "Varsayılan Panel Konumu",
  "defaultLocation": "Varsayılan Konum",
  "workbench.panel.opensMaximized": "Ekranı Kaplamış Olarak Aç",
  "opensMaximized": "Ekranı Kaplamış Olarak Aç",
  "zenMode.centerLayout": "Ortalanmış Düzen",
  "centerLayout": "Ortalanmış Düzen",
  "Center Layout": "Ortalanmış Düzen",
  "zenMode.hideStatusBar": "Durum Çubuğunu Gizle",
  "hideStatusBar": "Durum Çubuğunu Gizle",
  "Hide Status Bar": "Durum Çubuğunu Gizle",
  "zenMode.hideActivityBar": "Aktivite Çubuğunu Gizle",
  "hideActivityBar": "Aktivite Çubuğunu Gizle",
  "Hide Activity Bar": "Aktivite Çubuğunu Gizle",
  "zenMode.hideLineNumbers": "Satır Numaralarını Gizle",
  "hideLineNumbers": "Satır Numaralarını Gizle",
  "Hide Line Numbers": "Satır Numaralarını Gizle",
  "screencastMode.keyboardOptions": "Klavye Seçenekleri",
  "keyboardOptions": "Klavye Seçenekleri",
  "screencastMode.keyboardOverlayTimeout": "Klavye Katmanı Zaman Aşımı",
  "keyboardOverlayTimeout": "Klavye Katmanı Zaman Aşımı",
  "screencastMode.mouseIndicatorColor": "Fare Gösterge Rengi",
  "mouseIndicatorColor": "Fare Gösterge Rengi",
  "screencastMode.mouseIndicatorSize": "Fare Gösterge Boyutu",
  "mouseIndicatorSize": "Fare Gösterge Boyutu",
  "breadcrumbs.filePath": "Dosya Yolu",
  "filePath": "Dosya Yolu",
  "File Path": "Dosya Yolu",
  "breadcrumbs.symbolPath": "Sembol Yolu",
  "symbolPath": "Sembol Yolu",
  "Symbol Path": "Sembol Yolu",
  "breadcrumbs.symbolSortOrder": "Sembol Sıralama Düzeni",
  "symbolSortOrder": "Sembol Sıralama Düzeni",
  "Symbol Sort Order": "Sembol Sıralama Düzeni",
  "breadcrumbs.showNamespaces": "Ad Alanlarını Göster",
  "showNamespaces": "Ad Alanlarını Göster",
  "Show Namespaces": "Ad Alanlarını Göster",
  "breadcrumbs.showPackages": "Paketleri Göster",
  "showPackages": "Paketleri Göster",
  "Show Packages": "Paketleri Göster",
  "breadcrumbs.showStrings": "Dizgileri Göster",
  "showStrings": "Dizgileri Göster",
  "Show Strings": "Dizgileri Göster",
  "breadcrumbs.showNumbers": "Sayıları Göster",
  "showNumbers": "Sayıları Göster",
  "Show Numbers": "Sayıları Göster",
  "breadcrumbs.showBooleans": "Boole Değerlerini Göster",
  "showBooleans": "Boole Değerlerini Göster",
  "Show Booleans": "Boole Değerlerini Göster",
  "breadcrumbs.showArrays": "Dizileri Göster",
  "showArrays": "Dizileri Göster",
  "Show Arrays": "Dizileri Göster",
  "breadcrumbs.showObjects": "Nesneleri Göster",
  "showObjects": "Nesneleri Göster",
  "Show Objects": "Nesneleri Göster",
  "breadcrumbs.showKeys": "Anahtarları Göster",
  "showKeys": "Anahtarları Göster",
  "Show Keys": "Anahtarları Göster",
  "breadcrumbs.showNull": "Null Değerlerini Göster",
  "showNull": "Null Değerlerini Göster",
  "Show Null": "Null Değerlerini Göster",
  "settingsSync.ignoredExtensions": "Yoksayılan Eklentiler",
  "ignoredExtensions": "Yoksayılan Eklentiler",
  "Ignored Extensions": "Yoksayılan Eklentiler",
  "settingsSync.ignoredSettings": "Yoksayılan Ayarlar",
  "ignoredSettings": "Yoksayılan Ayarlar",
  "Ignored Settings": "Yoksayılan Ayarlar",
  "inlineChat.holdToSpeech": "Konuşmak İçin Basılı Tut",
  "holdToSpeech": "Konuşmak İçin Basılı Tut",
  "inlineChat.notebookAgent": "Not Defteri Ajanı",
  "notebookAgent": "Not Defteri Ajanı",
  "notebook.diff.ignoreMetadata": "Meta Verileri Yoksay",
  "ignoreMetadata": "Meta Verileri Yoksay",
  "notebook.diff.ignoreOutputs": "Çıktıları Yoksay",
  "ignoreOutputs": "Çıktıları Yoksay",
  "testing.followRunningTest": "Çalışan Testi Takip Et",
  "followRunningTest": "Çalışan Testi Takip Et",
  "testing.saveBeforeTest": "Testten Önce Kaydet",
  "saveBeforeTest": "Testten Önce Kaydet",
  "testing.automaticallyOpenTestResults": "Test Sonuçlarını Otomatik Olarak Aç",
  "automaticallyOpenTestResults": "Test Sonuçlarını Otomatik Olarak Aç",
  "files.trimTrailingWhitespaceInRegexAndStrings": "Regex ve Dizgilerdeki Sondaki Boşlukları Kırp",
  "trimTrailingWhitespaceInRegexAndStrings": "Regex ve Dizgilerdeki Sondaki Boşlukları Kırp",
  "explorer.excludeGitIgnore": ".gitignore Dosyasına Göre Dışla",
  "excludeGitIgnore": ".gitignore Dosyasına Göre Dışla",
  "search.experimental.closedNotebookRichContentResults": "Kapatılan Not Defteri Zengin İçerik Sonuçları",
  "closedNotebookRichContentResults": "Kapatılan Not Defteri Zengin İçerik Sonuçları",
  "scm.diffDecorationsIgnoreTrimWhitespace": "Fark Süslemelerinde Kırpılan Boşlukları Yoksay",
  "diffDecorationsIgnoreTrimWhitespace": "Fark Süslemelerinde Kırpılan Boşlukları Yoksay",
  "debug.terminal.clearBeforeReusing": "Yeniden Kullanmadan Önce Terminali Temizle",
  "clearBeforeReusing": "Yeniden Kullanmadan Önce Terminali Temizle",
  "problems.showCurrentInStatus": "Durum Çubuğunda Geçerli Sorunu Göster",
  "showCurrentInStatus": "Durum Çubuğunda Geçerli Sorunu Göster",
  "Show Current In Status": "Durum Çubuğunda Geçerli Sorunu Göster",
  "mergeEditor.showDeletionMarkers": "Silme İşaretçilerini Göster",
  "showDeletionMarkers": "Silme İşaretçilerini Göster",
  "Show Deletion Markers": "Silme İşaretçilerini Göster",
  "comments.openPanel": "Yorumlar Panelini Aç",
  "openPanel": "Paneli Aç",
  "output.smartScroll.enabled": "Akıllı Kaydırmayı Etkinleştir",
  "enabled": "Etkin",
  "task.problemMatchers.neverPrompt": "Sorun Eşleştiricileri İçin Asla Sorma",
  "neverPrompt": "Sorun Eşleştiricileri İçin Asla Sorma",
  "Never Prompt": "Sorun Eşleştiricileri İçin Asla Sorma",
  "task.autoDetect": "Görevleri Otomatik Algıla",
  "autoDetect": "Görevleri Otomatik Algıla",
  "Auto Detect": "Görevleri Otomatik Algıla",
  "task.slowProviderWarning": "Yavaş Sağlayıcı Uyarısı",
  "slowProviderWarning": "Yavaş Sağlayıcı Uyarısı",
  "Slow Provider Warning": "Yavaş Sağlayıcı Uyarısı",
  "task.quickOpen.showAll": "Hızlı Aç'ta Tümünü Göster",
  "showAll": "Tümünü Göster",
  "Show All": "Tümünü Göster",
  "task.allowAutomaticTasks": "Otomatik Görevlere İzin Ver",
  "allowAutomaticTasks": "Otomatik Görevlere İzin Ver",
  "Allow Automatic Tasks": "Otomatik Görevlere İzin Ver",
  "task.saveBeforeRun": "Çalıştırmadan Önce Kaydet",
  "saveBeforeRun": "Çalıştırmadan Önce Kaydet",
  "Save Before Run": "Çalıştırmadan Önce Kaydet",
  "task.notifyWindowOnTaskCompletion": "Görev Tamamlandığında Pencereyi Bildir",
  "notifyWindowOnTaskCompletion": "Görev Tamamlandığında Pencereyi Bildir",
  "Notify Window On Task Completion": "Görev Tamamlandığında Pencereyi Bildir",
  "task.verboseLogging": "Ayrıntılı Günlük Kaydı",
  "verboseLogging": "Ayrıntılı Günlük Kaydı",
  "Verbose Logging": "Ayrıntılı Günlük Kaydı",
  "remote.extensionKind": "Eklenti Türü",
  "extensionKind": "Eklenti Türü",
  "Extension Kind": "Eklenti Türü",
  "remote.autoForwardPorts": "Bağlantı Noktalarını Otomatik İlet",
  "autoForwardPorts": "Bağlantı Noktalarını Otomatik İlet",
  "Auto Forward Ports": "Bağlantı Noktalarını Otomatik İlet",
  "remote.autoForwardPortsSource": "Otomatik İletim Kaynağı",
  "autoForwardPortsSource": "Otomatik İletim Kaynağı",
  "Auto Forward Ports Source": "Otomatik İletim Kaynağı",
  "remote.autoForwardPortsFallback": "Otomatik İletim Yedekleme",
  "autoForwardPortsFallback": "Otomatik İletim Yedekleme",
  "Auto Forward Ports Fallback": "Otomatik İletim Yedekleme",
  "remote.forwardOnOpen": "Açıldığında Bağlantı Noktasını İlet",
  "forwardOnOpen": "Açıldığında Bağlantı Noktasını İlet",
  "Forward On Open": "Açıldığında Bağlantı Noktasını İlet",
  "remote.downloadExtensionsLocally": "Eklentileri Yerel Olarak İndir",
  "downloadExtensionsLocally": "Eklentileri Yerel Olarak İndir",
  "Download Extensions Locally": "Eklentileri Yerel Olarak İndir",
  "outline.showNamespaces": "Ad Alanlarını Göster",
  "outline.showPackages": "Paketleri Göster",
  "outline.showStrings": "Dizgileri Göster",
  "outline.showNumbers": "Sayıları Göster",
  "outline.showBooleans": "Boole Değerlerini Göster",
  "outline.showArrays": "Dizileri Göster",
  "outline.showObjects": "Nesneleri Göster",
  "outline.showKeys": "Anahtarları Göster",
  "outline.showNull": "Null Değerlerini Göster",
  "antigravity.enableAgentMode": "Ajan Modunu Etkinleştir",
  "enableAgentMode": "Ajan Modunu Etkinleştir",
  "Enable Agent Mode": "Ajan Modunu Etkinleştir",
  "application.shellEnvironmentResolutionTimeout": "Kabuk Ortamı Çözümleme Zaman Aşımı",
  "shellEnvironmentResolutionTimeout": "Kabuk Ortamı Çözümleme Zaman Aşımı",
  "Shell Environment Resolution Timeout": "Kabuk Ortamı Çözümleme Zaman Aşımı",
  "Associations": "İlişkilendirmeler",
  "associations": "İlişkilendirmeler",
  "files.associations": "İlişkilendirmeler",
  "Token Color Customizations": "Belirteç Renk Özelleştirmeleri",
  "tokenColorCustomizations": "Belirteç Renk Özelleştirmeleri",
  "editor.tokenColorCustomizations": "Belirteç Renk Özelleştirmeleri",
  "Color Customizations": "Renk Özelleştirmeleri",
  "colorCustomizations": "Renk Özelleştirmeleri",
  "workbench.colorCustomizations": "Renk Özelleştirmeleri",
  "showMoves": "Kod Taşımalarını Göster",
  "diffEditor.experimental.showMoves": "Kod Taşımalarını Göster",
  "contextLineCount": "Bağlam Satır Sayısı",
  "diffEditor.hideUnchangedRegions.contextLineCount": "Bağlam Satır Sayısı",
  "minimumLineCount": "Minimum Satır Sayısı",
  "diffEditor.hideUnchangedRegions.minimumLineCount": "Minimum Satır Sayısı",
  "revealLineCount": "Gösterilecek Satır Sayısı",
  "diffEditor.hideUnchangedRegions.revealLineCount": "Gösterilecek Satır Sayısı",
  "diffEditor.hideUnchangedRegions.enabled": "Etkin",
  "DoubleClickIconToClose": "Kapatmak İçin Simgeye Çift Tıkla",
  "files.readonlyExclude": "Salt Okunur Dışlananlar",
  "readonlyExclude": "Salt Okunur Dışlananlar",
  "Readonly Exclude": "Salt Okunur Dışlananlar",
  "files.readonlyInclude": "Salt Okunur Dahil Edilenler",
  "readonlyInclude": "Salt Okunur Dahil Edilenler",
  "Readonly Include": "Salt Okunur Dahil Edilenler",
  "files.readonlyFromPermissions": "Dosya İzinlerinden Salt Okunur",
  "readonlyFromPermissions": "Dosya İzinlerinden Salt Okunur",
  "Readonly From Permissions": "Dosya İzinlerinden Salt Okunur",
  "workbench.preferredDarkColorTheme": "Tercih Edilen Koyu Renk Teması",
  "preferredDarkColorTheme": "Tercih Edilen Koyu Renk Teması",
  "Preferred Dark Color Theme": "Tercih Edilen Koyu Renk Teması",
  "workbench.preferredLightColorTheme": "Tercih Edilen Açık Renk Teması",
  "preferredLightColorTheme": "Tercih Edilen Açık Renk Teması",
  "Preferred Light Color Theme": "Tercih Edilen Açık Renk Teması",
  "workbench.preferredHighContrastColorTheme": "Tercih Edilen Yüksek Karşıtlık Teması",
  "preferredHighContrastColorTheme": "Tercih Edilen Yüksek Karşıtlık Teması",
  "Preferred High Contrast Color Theme": "Tercih Edilen Yüksek Karşıtlık Teması",
  "workbench.preferredHighContrastLightColorTheme": "Tercih Edilen Açık Yüksek Karşıtlık Teması",
  "preferredHighContrastLightColorTheme": "Tercih Edilen Açık Yüksek Karşıtlık Teması",
  "Preferred High Contrast Light Color Theme": "Tercih Edilen Açık Yüksek Karşıtlık Teması",
  "workbench.productIconTheme": "Ürün Simge Teması",
  "productIconTheme": "Ürün Simge Teması",
  "Product Icon Theme": "Ürün Simge Teması",
  "workbench.tree.enableStickyScroll": "Sabit Kaydırmayı Etkinleştir",
  "enableStickyScroll": "Sabit Kaydırmayı Etkinleştir",
  "Enable Sticky Scroll": "Sabit Kaydırmayı Etkinleştir",
  "workbench.tree.renderIndentGuides": "Girinti Kılavuzlarını Göster",
  "renderIndentGuides": "Girinti Kılavuzlarını Göster",
  "Render Indent Guides": "Girinti Kılavuzlarını Göster",
  "workbench.tree.stickyScrollMaxItemCount": "Sabit Kaydırma Maksimum Öğe Sayısı",
  "stickyScrollMaxItemCount": "Sabit Kaydırma Maksimum Öğe Sayısı",
  "Sticky Scroll Max Item Count": "Sabit Kaydırma Maksimum Öğe Sayısı",
  "workbench.tree.expandMode": "Genişletme Modu",
  "expandMode": "Genişletme Modu",
  "Expand Mode": "Genişletme Modu",
  "workbench.list.horizontalScrolling": "Yatay Kaydırma",
  "horizontalScrolling": "Yatay Kaydırma",
  "Horizontal Scrolling": "Yatay Kaydırma",
  "workbench.list.keyboardNavigation": "Klavye Gezinmesi",
  "keyboardNavigation": "Klavye Gezinmesi",
  "Keyboard Navigation": "Klavye Gezinmesi",
  "workbench.list.multiSelectModifier": "Çoklu Seçim Değiştirici Tuşu",
  "multiSelectModifier": "Çoklu Seçim Değiştirici Tuşu",
  "Multi Select Modifier": "Çoklu Seçim Değiştirici Tuşu",
  "workbench.list.openMode": "Açma Modu",
  "openMode": "Açma Modu",
  "Open Mode": "Açma Modu",
  "workbench.list.defaultFindMode": "Varsayılan Bulma Modu",
  "defaultFindMode": "Varsayılan Bulma Modu",
  "Default Find Mode": "Varsayılan Bulma Modu",
  "workbench.list.defaultFindMatchType": "Varsayılan Eşleşme Türü",
  "defaultFindMatchType": "Varsayılan Eşleşme Türü",
  "Default Find Match Type": "Varsayılan Eşleşme Türü",
  "workbench.list.typeNavigationMode": "Yazarak Gezinme Modu",
  "typeNavigationMode": "Yazarak Gezinme Modu",
  "Type Navigation Mode": "Yazarak Gezinme Modu",
  "window.autoDetectColorScheme": "Renk Düzenini Otomatik Algıla",
  "autoDetectColorScheme": "Renk Düzenini Otomatik Algıla",
  "Auto Detect Color Scheme": "Renk Düzenini Otomatik Algıla",
  "window.autoDetectHighContrast": "Yüksek Karşıtlığı Otomatik Algıla",
  "autoDetectHighContrast": "Yüksek Karşıtlığı Otomatik Algıla",
  "Auto Detect High Contrast": "Yüksek Karşıtlığı Otomatik Algıla",
  "window.systemColorTheme": "Sistem Renk Teması",
  "systemColorTheme": "Sistem Renk Teması",
  "System Color Theme": "Sistem Renk Teması",
  "window.commandCenterDefaultPrefix": "Komut Merkezi Varsayılan Öneki",
  "commandCenterDefaultPrefix": "Komut Merkezi Varsayılan Öneki",
  "Command Center Default Prefix": "Komut Merkezi Varsayılan Öneki",
  "window.commandCenterSeedWithSelection": "Komut Merkezini Seçimle Başlat",
  "commandCenterSeedWithSelection": "Komut Merkezini Seçimle Başlat",
  "Command Center Seed With Selection": "Komut Merkezini Seçimle Başlat",
  "window.rememberProxyCredentials": "Proxy Kimlik Bilgilerini Hatırla",
  "rememberProxyCredentials": "Proxy Kimlik Bilgilerini Hatırla",
  "Remember Proxy Credentials": "Proxy Kimlik Bilgilerini Hatırla",
  "telemetry.telemetryLevel": "Telemetri Düzeyi",
  "telemetryLevel": "Telemetri Düzeyi",
  "Telemetry Level": "Telemetri Düzeyi",
  "telemetry.enableTelemetry": "Telemetriyi Etkinleştir",
  "enableTelemetry": "Telemetriyi Etkinleştir",
  "Enable Telemetry": "Telemetriyi Etkinleştir",
  "zenMode.fullScreen": "Tam Ekran",
  "fullScreen": "Tam Ekran",
  "Full Screen": "Tam Ekran",
  "zenMode.restore": "Geri Yükle",
  "restore": "Geri Yükle",
  "Restore": "Geri Yükle",
  "zenMode.silentNotifications": "Sessiz Bildirimler",
  "silentNotifications": "Sessiz Bildirimler",
  "Silent Notifications": "Sessiz Bildirimler",
  "chat.useAgentsMdFile": "AGENTS.md Dosyasını Kullan",
  "useAgentsMdFile": "AGENTS.md Dosyasını Kullan",
  "Use Agents Md File": "AGENTS.md Dosyasını Kullan",
  "chat.useNestedAgentsMdFiles": "İç İçe AGENTS.md Dosyalarını Kullan",
  "useNestedAgentsMdFiles": "İç İçe AGENTS.md Dosyalarını Kullan",
  "Use Nested Agents Md Files": "İç İçe AGENTS.md Dosyalarını Kullan",
  "chat.useClaudeSkills": "Claude Becerilerini Kullan",
  "useClaudeSkills": "Claude Becerilerini Kullan",
  "Use Claude Skills": "Claude Becerilerini Kullan",
  "chat.mcp.access": "MCP Erişimi",
  "chat.mcp.autostart": "MCP Otomatik Başlatma",
  "chat.mcp.serverSampling": "MCP Sunucu Örneklemesi",
  "chat.tools.eligibleForAutoApproval": "Otomatik Onaya Uygun Araçlar",
  "chat.tools.todos.showWidget": "Yapılacaklar Pencere Öğesini Göster",
  "outline.collapseItems": "Öğeleri Daralt",
  "collapseItems": "Öğeleri Daralt",
  "Collapse Items": "Öğeleri Daralt",
  "outline.icons": "Simgeleri Göster",
  "icons": "Simgeleri Göster",
  "Icons": "Simgeleri Göster",
  "problems.visibility": "Sorunlar Görünürlüğü",
  "visibility": "Görünürlük",
  "Visibility": "Görünürlük",
  "settingsSync.keybindingsPerPlatform": "Platform Başına Tuş Atamaları",
  "keybindingsPerPlatform": "Platform Başına Tuş Atamaları",
  "Keybindings Per Platform": "Platform Başına Tuş Atamaları",
  "http.proxy": "Proxy Adresi",
  "http.proxyAuthorization": "Proxy Kimlik Doğrulaması",
  "http.proxySupport": "Proxy Desteği",
  "http.systemCertificates": "Sistem Sertifikalarını Kullan",
  "http.noProxy": "Proxy Kullanılmayacak Adresler",
  "http.useLocalProxyConfiguration": "Yerel Proxy Yapılandırmasını Kullan"
};

module.exports = { categories, settings };
